- .travis.yml
- app/build.gradle
- app/src/androidTest/java/io/treehouses/remote/ExampleInstrumentedTest.java
- set_tags.sh
This branch was pulled 2 days ago from the master. this should be working...lets see
> New travis

- README.md
[x] Completely overhaul the readme.md 
[x] Separate the android instructions from the Pi instructions
[x] Detail the setup for the android device
[x] Detail the setup for the Raspberry Pi device
> Updated readme file(issue #20)

- app/src/main/res/values/strings.xml
Added capitalization to a couple titles in the activity device list
> update some string to use title case (fixes #35)

- app/src/main/java/io/treehouses/remote/BluetoothChatFragment.java
- app/src/main/java/io/treehouses/remote/HotspotDialogFragment.java
- app/src/main/java/io/treehouses/remote/WifiDialogFragment.java
- app/src/main/res/menu/bluetooth_chat.xml
- app/src/main/res/values/strings.xml
This seems to almost always be met with this issue (https://github.com/treehouses/remote/issues/50) on the first try. On the second try, it works.
> Make hotspot (issue #9)

- app/src/main/java/io/treehouses/remote/BluetoothChatFragment.java
- app/src/main/res/layout-large-land/fragment_bluetooth_chat.xml
- app/src/main/res/layout-large/fragment_bluetooth_chat.xml
- app/src/main/res/layout-small-land/fragment_bluetooth_chat.xml
- app/src/main/res/layout-small/fragment_bluetooth_chat.xml
- app/src/main/res/layout-xlarge-land/fragment_bluetooth_chat.xml
- app/src/main/res/layout-xlarge/fragment_bluetooth_chat.xml
- app/src/main/res/layout/fragment_bluetooth_chat.xml
Just the button for now is added, I am not able to see this button on my hardware, so I am making this pull request for others to test.
> [WIP] rename hostname button (fixes #43)

- app/src/main/java/io/treehouses/remote/BluetoothChatFragment.java
- app/src/main/res/layout-large-land/fragment_bluetooth_chat.xml
- app/src/main/res/layout-large/fragment_bluetooth_chat.xml
- app/src/main/res/layout-small-land/fragment_bluetooth_chat.xml
- app/src/main/res/layout-small/fragment_bluetooth_chat.xml
- app/src/main/res/layout-xlarge-land/fragment_bluetooth_chat.xml
- app/src/main/res/layout-xlarge/fragment_bluetooth_chat.xml
- app/src/main/res/layout/fragment_bluetooth_chat.xml
Added a button to expand the partition to the maximum space available.
> Expandfs [issue #60]

- app/src/main/java/io/treehouses/remote/BluetoothChatFragment.java
- app/src/main/java/io/treehouses/remote/WifiDialogFragment.java
- app/src/main/res/layout-large/fragment_bluetooth_chat.xml
- app/src/main/res/values/strings.xml
Does not allow positive button to be clicked unless password of eight or more characters are entered, and an error message to notify user of this is displayed.
> Error message for password length[Issue #56]

- app/src/main/java/io/treehouses/remote/BluetoothChatFragment.java
- app/src/main/res/layout-large-land/fragment_bluetooth_chat.xml
- app/src/main/res/layout-large/fragment_bluetooth_chat.xml
- app/src/main/res/layout-small-land/fragment_bluetooth_chat.xml
- app/src/main/res/layout-small/fragment_bluetooth_chat.xml
- app/src/main/res/layout-xlarge-land/fragment_bluetooth_chat.xml
- app/src/main/res/layout-xlarge/fragment_bluetooth_chat.xml
- app/src/main/res/layout/fragment_bluetooth_chat.xml
- app/src/main/res/values/strings.xml
The getAlertDialog method repeats some very similar code so there might be a more elegant way to do this.
> [WIP] adds button to change pi users password (fixes #52)

- app/src/main/java/io/treehouses/remote/HotspotDialogFragment.java
- app/src/main/java/io/treehouses/remote/TextBoxValidation.java
- app/src/main/java/io/treehouses/remote/WifiDialogFragment.java
- app/src/main/res/layout-large-land/hotspot_dialog.xml
- app/src/main/res/layout-large/hotspot_dialog.xml
- app/src/main/res/layout-small-land/hotspot_dialog.xml
- app/src/main/res/layout-small/hotspot_dialog.xml
- app/src/main/res/layout-xlarge-land/hotspot_dialog.xml
- app/src/main/res/layout-xlarge/hotspot_dialog.xml
- app/src/main/res/layout/hotspot_dialog.xml
- app/src/main/res/values/strings.xml
- build.gradle
Hotspot confirm password validation should be in order.
> [WIP]Hotspot password validation (fixes #77)

- app/src/main/java/io/treehouses/remote/Dashboard.java
Now we can get back to dashboard from cmd command by clicking back. Please review everyone!!! Thanks
> Enabled Backbutton press in cmd 

- app/src/main/java/io/treehouses/remote/BluetoothChatFragment.java
- app/src/main/java/io/treehouses/remote/ChPasswordDialogFragment.java
- app/src/main/java/io/treehouses/remote/TextBoxValidation.java
- app/src/main/res/layout-large-land/chpass_dialog.xml
- app/src/main/res/layout-large/chpass_dialog.xml
- app/src/main/res/layout-small-land/chpass_dialog.xml
- app/src/main/res/layout-small/chpass_dialog.xml
- app/src/main/res/layout-xlarge-land/chpass_dialog.xml
- app/src/main/res/layout-xlarge/chpass_dialog.xml
- app/src/main/res/layout/chpass_dialog.xml
Fixes #94 
Also created a seperate class for the change password dialog
> Added confirm password validation (fixes #94 )

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/treehouses/remote/BluetoothChatFragment.java
- app/src/main/java/io/treehouses/remote/BluetoothChatService.java
- app/src/main/java/io/treehouses/remote/Constants.java
- app/src/main/java/io/treehouses/remote/CustomHandler.java
- app/src/main/java/io/treehouses/remote/Dashboard.java
- app/src/main/java/io/treehouses/remote/DeviceListActivity.java
- app/src/main/java/io/treehouses/remote/DockerFragment.java
- app/src/main/java/io/treehouses/remote/HotspotDialogFragment.java
- app/src/main/java/io/treehouses/remote/MainActivity.java
- app/src/main/java/io/treehouses/remote/PirateshipFragment.java
- app/src/main/java/io/treehouses/remote/WifiDialogFragment.java
> [Merge-able] reorganize code, clean up, make variables easier to understand

- app/src/main/java/io/treehouses/remote/Dashboard.java
- app/src/main/java/io/treehouses/remote/DockerFragment.java
- app/src/main/java/io/treehouses/remote/TreehousesFragment.java
- app/src/main/res/layout/docker_layout.xml
- app/src/main/res/layout/hope_layout.xml
- app/src/main/res/layout/treehouses_layout.xml
Change from Activity to Fragment, part of refactoring.
> [Ready to Merge] change Activity to Fragment (fixes issue #107)

- app/src/main/java/io/treehouses/remote/BluetoothChatFragment.java
Continue working on this PR when PR 114 is merge.
> [WIP] remove unused functionalities

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
> implement usage of treehouses default network (issue #130)

- app/src/main/java/io/treehouses/remote/Fragments/RPIDialogFragment.java
> Fixing Device Duplication (fixes #139)

- .travis.yml
- app/src/main/java/io/treehouses/remote/Fragments/RPIDialogFragment.java
- app/src/main/java/io/treehouses/remote/InitialActivity.java
- app/src/main/java/io/treehouses/remote/Network/BluetoothChatService.java
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
fixes #153 
Still being tested by me.
> Fixed Endless Spinning (Issue #153)

- app/src/main/java/io/treehouses/remote/Fragments/RPIDialogFragment.java
- app/src/main/java/io/treehouses/remote/InitialActivity.java
> Screen Rotation Bluetooth Loss (Issue #168)

- app/build.gradle
> change output name to remote.apk (fixes #122)

- app/src/main/java/io/treehouses/remote/InitialActivity.java
> Not Able To Access Home Page after Bluetooth Loss (fixes #175)

- app/src/main/java/io/treehouses/remote/Fragments/RPIDialogFragment.java
Fixes https://github.com/treehouses/remote/issues/178
> Already paired device not showing issue fixed (Fixes #178)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/SystemFragment.java
- build.gradle
> Catch Spaces When Creating Wifi Networks (fixes #185)

- app/src/main/AndroidManifest.xml
- build.gradle
> Removes contacts and calls data permission (fixes #151)

- app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/Utils.java
> Added copy function for terminal (fixes #150)

- app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.java
- app/src/main/res/layout/activity_status_fragment.xml
- build.gradle
> Status Page cli upgrade (fixes #190)

- app/src/main/res/layout/activity_home_fragment.xml
It now should look clear and not blurry
> Fixed resolution of home screen icon (fixes #126)

- build.gradle
> updated gradle plugin (fixes #213)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.java
- app/src/main/java/io/treehouses/remote/InitialActivity.java
- app/src/main/java/io/treehouses/remote/callback/HomeInteractListener.java
- app/src/main/java/io/treehouses/remote/utils/LogUtils.java
Fixes https://github.com/treehouses/remote/issues/235 https://github.com/treehouses/remote/issues/234
@dogi  @inDepthh @Sriharsha-Singam 
Please review 
```Status Page```
```Network Page (Added network mode)```
> Network , Status and Terminal page bug fix 

- app/src/main/java/io/treehouses/remote/Fragments/TunnelFragment.java
> Refactor TunnelFragment (fixes #228)

- app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/TunnelFragment.java
> Improve readability of output (fixes #241)

- app/src/main/java/io/treehouses/remote/Fragments/HotspotDialogFragment.java
- app/src/main/res/layout/dialog_bridge.xml
- app/src/main/res/layout/dialog_hotspot.xml
> swap field positions (fixes #246)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
It updates the network mode instead of showing a output dialog that does not offer any useful information
> network mode: update in replace of output dialog (fixes #244)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
> fixed network page popup bug (fixes #249)

- app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.java
> refactor TerminalFragment (fixes #264)

- app/src/main/java/io/treehouses/remote/Fragments/RPIDialogFragment.java
fixes #259 
cleans up the code
> refactor RPIDialogFragment (fixes #259)

- app/src/main/java/io/treehouses/remote/adapter/ViewHolderBridge.java
- app/src/main/res/layout/dialog_bridge.xml
> treehouses bridge fix (Fixes #258)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
> networkpage: one group expanded at a time (fixes #271)

- app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderReboot.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderReset.java
- app/src/main/java/io/treehouses/remote/pojo/NetworkListItem.java
- app/src/main/res/layout/dialog_reboot.xml
- app/src/main/res/layout/dialog_reset.xml
> network: reset/reboot expandable (fixes #273) (fixes #274)

- app/src/main/res/layout/dialog_bridge.xml
- app/src/main/res/layout/dialog_ethernet.xml
- app/src/main/res/layout/dialog_hotspot.xml
- app/src/main/res/layout/dialog_wifi.xml
> network: child layouts more concise (fixes #275)

- app/src/main/java/io/treehouses/remote/Fragments/RPIDialogFragment.java
> bluetooth connected: shows toast message (fixes #148)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderReboot.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderReset.java
> network: dialogs for reset/reboot (fixes #284)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
- app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.java
- app/src/main/java/io/treehouses/remote/pojo/NetworkListItem.java
> networkmode: expand group on networkmode (fixes #276)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
> network: new own dialog for reset/reboot (fixes #287)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
- app/src/main/java/io/treehouses/remote/InitialActivity.java
- app/src/main/res/layout/activity_home_fragment.xml
> home: getting started button (fixes #297)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
> home: run only once friendly reminder (fixes #299)

- app/src/main/res/values/strings.xml
> about: update copyright (fixes #311)

- app/src/main/java/io/treehouses/remote/Fragments/AboutFragment.java
- app/src/main/res/layout/activity_about_fragment.xml
- app/src/main/res/values/strings.xml
> about: fix hyperlink (fixes #311)

- app/src/main/java/io/treehouses/remote/Constants.java
> constants: remove redundant code (fixes #316)

- app/src/main/java/io/treehouses/remote/Fragments/TunnelFragment.java
- app/src/main/java/io/treehouses/remote/MainApplication.java
> tunnel: save list commands (fixes #318)

- .travis.yml
> travis release build apk 3.0 (fixes #326)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
> network: ∞ loop fix (fixes #335)

- app/src/main/java/io/treehouses/remote/ButtonConfiguration.java
- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderBridge.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderEthernet.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderHotspot.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderWifi.java
> network: fix NullPointerException (fixes #357)

- app/src/main/java/io/treehouses/remote/ButtonConfiguration.java
- app/src/main/java/io/treehouses/remote/Fragments/WifiDialogFragment.java
> network: bug fixes in wifi search (fixes #351)

- app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/TunnelFragment.java
- app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.java
> terminal/tunnel: refactor handlers (fixes 363)

- app/src/main/java/io/treehouses/remote/Fragments/TunnelFragment.java
- app/src/main/res/layout/activity_tunnel_fragment.xml
> tunnel: tor notice switch (fixes #369)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
> network: networkmode bug fix (fixes #370)

- app/src/main/java/io/treehouses/remote/ButtonConfiguration.java
> network: fix wifi-scan toast message (fixes #373)

- app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderCommands.java
- app/src/main/res/layout/button_layout.xml
> terminal: clear button (fixes #377)

- app/src/main/java/io/treehouses/remote/Fragments/RPIDialogFragment.java
> home: cancel bluetooth discovery (fixes #386)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
#382 
It happened twice randomly.. this should fix it but it was not tested because it is random to reproduce. See the issue for the exception message.
> network: network mode crash (fixes #382 

- app/src/main/java/io/treehouses/remote/Fragments/AboutFragment.java
> about: fix version button (#397)

- app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.java
> terminal: fix cursor position (#393)

- app/src/main/java/io/treehouses/remote/adapter/ViewHolderCommands.java
- app/src/main/res/layout/button_layout.xml
> terminal: add buttons to list (fixes #401)

- app/src/main/java/io/treehouses/remote/adapter/ViewHolderBridge.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderHotspot.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderWifi.java
> network: disable auto-correct (fixes #394)

- app/src/main/java/io/treehouses/remote/Fragments/SystemFragment.java
> system: fix open vnc (fixes #407)

- app/src/main/java/io/treehouses/remote/adapter/ViewHolderCommands.java
> terminal: fix vnc command (fixes #409)

- app/src/main/java/io/treehouses/remote/Fragments/SystemFragment.java
> system: prefill ip (fixes #410)

- app/src/main/java/io/treehouses/remote/ButtonConfiguration.java
- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderBridge.java
> network: prefill essid (fixes #356)

- app/src/main/java/io/treehouses/remote/Fragments/SystemFragment.java
> system: check subnet for vnc (fixes #418)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
> Network crash fix (Fixes #428)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
- build.gradle
> network: expand ap group (fixes #431)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderHotspot.java
> network: prefill ap essid (fixes #430)

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/treehouses/remote/Fragments/SystemFragment.java
- app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderTether.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderVnc.java
- app/src/main/java/io/treehouses/remote/pojo/NetworkListItem.java
- app/src/main/res/layout-large-land/hotspot_dialog.xml
- app/src/main/res/layout-large/hotspot_dialog.xml
- app/src/main/res/layout-small-land/hotspot_dialog.xml
- app/src/main/res/layout-small/hotspot_dialog.xml
- app/src/main/res/layout-xlarge-land/hotspot_dialog.xml
- app/src/main/res/layout-xlarge/hotspot_dialog.xml
- app/src/main/res/layout/activity_system_fragment.xml
- app/src/main/res/layout/configure_tethering.xml
- app/src/main/res/layout/hotspot_dialog.xml
- app/src/main/res/layout/open_vnc.xml
- build.gradle
> system: configure hotspot (#390)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
> welcome: make links clickable (fixes #411)

- app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/TunnelFragment.java
- app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.java
- app/src/main/res/layout/activity_terminal_fragment.xml
- app/src/main/res/layout/activity_tunnel_fragment.xml
> terminal: automatic status led (fixes #421)

- app/src/main/res/layout/activity_terminal_fragment.xml
> Led padding Fixes #462

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
- app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderReset.java
> network: update ethernet mode (fixes #361)

- app/src/main/res/layout/activity_status_fragment.xml
> status: upgrade button (fixes #471)

- app/src/main/java/io/treehouses/remote/InitialActivity.java
[x] Check for issue number in pull request title
[x] Are there any unneeded files in the pull request?
[x] Did they make a branch for their patch?
[x] Does the pull request actually fix the issue?
[x] Check the pull request on raw.githack, does it display without any errors?
[x] Are there any merge conflicts?
[x] Make sure that people use their GitHub accounts when making commits through git
> home: catch back button (fixes #473)

- app/build.gradle
- app/google-services.json
- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
- app/src/main/java/io/treehouses/remote/MainApplication.java
- app/src/main/java/io/treehouses/remote/utils/Utils.java
- build.gradle
> added standard firebase analytics (fixes #478)

- app/src/main/java/io/treehouses/remote/ButtonConfiguration.java
- app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderBridge.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderEthernet.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderHotspot.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderWifi.java
- app/src/main/java/io/treehouses/remote/utils/ButtonConfiguration.java
- app/src/main/java/io/treehouses/remote/utils/TextWatcherUtils.java
> separate class for text change listener (fixes #444)

- app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
Updates the available bluetooth devices to only display raspberry pi.
> Removes all available bluetooth connects except for raspberry pi (Fixes #483)

- app/src/main/java/io/treehouses/remote/Fragments/TunnelFragment.java
- app/src/main/res/layout/activity_tunnel_fragment.xml
> tunnel: button change (fixes #486)

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/treehouses/remote/SplashScreen.java
- app/src/main/java/io/treehouses/remote/SplashScreenActivity.java
- app/src/main/res/anim/splash_anim.xml
- app/src/main/res/layout/activity_splash_screen.xml
**Splash Screen**: On the startup of the app, the treehouses logo is displayed. 
**Animation**: Logo moves from the top of the screen to center of the screen.
> welcome: splash screen

- app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.java
- app/src/main/res/layout/activity_status_fragment.xml
> status: add memory (fixes #495) (fixes #362)

- app/src/main/java/io/treehouses/remote/Fragments/AboutFragment.java
Reference: #502 
Links button to contributors on Github: https://github.com/treehouses/remote/graphs/contributors
> welcome: link contributors button (fixes #502)

- app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.java
Paired Raspberry Pi devices now appear immediately in RPI Dialog.
Fixes Issue #510
> welcome: improve connecting to paired devices (fixes #510)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
- app/src/main/res/layout/activity_home_fragment.xml
- app/src/main/res/values/strings.xml
Issue: #509 
The button appears once connected to a device:
> welcome: add led dance (fixes #509)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
- app/src/main/res/drawable/circle_green.xml
- app/src/main/res/drawable/circle_red.xml
- app/src/main/res/drawable/flash_anim_green.xml
- app/src/main/res/drawable/flash_anim_red.xml
- app/src/main/res/layout/dialog_test_connection.xml
Added graphical led lights to TestConnectionDialog. Flashes in the same pattern as on the Raspberry Pi.
> welcome: testconnection with simulated led lights

- app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.java
- app/src/main/java/io/treehouses/remote/adapter/RPIListAdapter.java
- app/src/main/java/io/treehouses/remote/pojo/DeviceInfo.java
- app/src/main/res/layout/list_rpi_item.xml
Icon changes when Raspberry Pi is in range of the android device
> welcome: paired rpi with grey icon turns to color when detected

- app/build.gradle
- app/src/main/java/io/treehouses/remote/Fragments/SettingsFragment.java
- app/src/main/java/io/treehouses/remote/InitialActivity.java
- app/src/main/java/io/treehouses/remote/SplashScreenActivity.java
- app/src/main/res/xml/app_preferences.xml
Added a settings screen so that the settings button in the toolbar is now functional.
Add more settings to be set by the user. Any input would be greatly appreciated!
> setting: add screen (fixes #499)

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.java
- app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.java
- app/src/main/res/layout/activity_terminal_fragment.xml
- app/src/main/res/values/strings.xml
Added autocomplete hints to terminal
Add more commands to the commands list
> terminal: add autocomplete (fixes #518)

- app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.java
The name is now sourced from the hostname instead of the bluetooth name. `hostname` is written to the Raspberry pi and the name returned is set as the name of the device.
> status: real hostname (fixes #530)

- app/build.gradle
- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
- app/src/main/res/layout/activity_terminal_fragment.xml
Reference Issue #542 
Added a fixed dimension for width of commands list, and then constrained the right side to parent
> terminal: tweak commands UI (fixes #541)

- app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.java
- app/src/main/res/layout/dialog_listview.xml
Changed the layout view from the RPI dialog view to a new dialog view containing just a listview and a cancel button. The Raspberry Pi Switch was removed.
> network: scan ssid dialog (fixes #529)

- app/src/main/java/io/treehouses/remote/utils/ButtonConfiguration.java
- app/src/main/res/layout/dialog_wifi.xml
Reference to Issues: #443 #553 
Change search wifi button to icon.
> network: change wifi button to icon (fixes #443) (fixes #553)

- app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.java
- app/src/main/res/layout/activity_status_fragment.xml
> status: add image version (fixes #551) (fixes #552)

- app/src/main/res/layout/activity_terminal_fragment.xml
- app/src/main/res/layout/dialog_hotspot.xml
- app/src/main/res/values-large/dimens.xml
- app/src/main/res/values-small/dimens.xml
- app/src/main/res/values-xlarge/dimens.xml
- app/src/main/res/values/dimens.xml
- Fix commands list appearance on tablets
- Added ability to hide or show the password for hotspot in Network Fragment
> network & terminal: tiny modifications (fixes #561)(fixes #563)

- app/src/main/res/layout/dialog_bridge.xml
> network: bridge wifi search button to icon (fixes #560)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
Check to make sure that buttonConfiguration was not null. 
```
if (buttonConfiguration == null) return false;
```
> network: no other null pointer crash (fixes #568)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
- app/src/main/java/io/treehouses/remote/Network/ParseDbService.java
- app/src/main/java/io/treehouses/remote/utils/Utils.java
> log: treehouses image version and blutooth mac address

- app/src/main/java/io/treehouses/remote/adapter/ViewHolderBridge.java
#581 
Fixed by changing `etSsid` to `essid`
> network: bridge essid bug (fixes #581)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
- app/src/main/java/io/treehouses/remote/adapter/ProfilesListAdapter.java
- app/src/main/java/io/treehouses/remote/utils/SaveUtils.java
- app/src/main/res/drawable/ic_delete_black_24dp.xml
- app/src/main/res/layout/activity_home_fragment.xml
- app/src/main/res/layout/row_profile.xml
- Added a delete icon to delete individual profiles. Also, included a message if there are no profiles available.
- Added a `progressDialog` instead of `progressBar`
- Changed the `Test Connection` button name to `Test Bluetooth`
> add delete profile and progressdialog

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.java
- app/src/main/java/io/treehouses/remote/adapter/ServicesListAdapter.java
- app/src/main/res/layout/activity_services_tab_fragment.xml
- app/src/main/res/layout/services_row_layout.xml
Reference: #586 
Start, stop, up, down commands all functional.
- Fix Aesthetic (Add four buttons and dropdown menu)
> services (fixes #586)

- README.md
> update README.md (fixes #597)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.java
- app/src/main/java/io/treehouses/remote/bases/BaseHomeFragment.java
> home & status: switch to treehouses remote status (fixes #588)

- app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.java
- app/src/main/java/io/treehouses/remote/adapter/ServicesListAdapter.java
- app/src/main/java/io/treehouses/remote/pojo/ServiceInfo.java
- app/src/main/res/layout/activity_services_tab_fragment.xml
- Enabled/disabled button depending on if service is available/installed/running
- Change the text color of running services to green
Available:
- Install button is available
Installed:
- Start and Uninstall buttons are available
Running:
- Stop and Uninstall button are available
> services: docker status based buttons (fixes #595)(fixes #599)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
- app/src/main/java/io/treehouses/remote/Network/BluetoothChatService.java
#604 
Fixed multiple checks issue
> home: check upgrade (fixes #604)

- app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.java
- app/src/main/java/io/treehouses/remote/adapter/ServicesListAdapter.java
- app/src/main/res/layout/services_row_layout.xml
- Added restart service button
- Improved layout to three buttons in the services fragment
> service: restart and new layout (fixes #607)

- app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.java
> status: new upgrade check (fixes #601)

- app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.java
- app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderHotspot.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderWifi.java
- app/src/main/java/io/treehouses/remote/utils/TextWatcherUtils.java
Diagnosed Issue: Listview is not reusing views with the adapter (not checking whether convertView is null).
Checking for if convertView is null results in other bugs, so an array with all the views was constructed.
> network: input while virtual keyboard (fixes #613)

- app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.java
> services: dialog when uninstall (fixes #606)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
- app/src/main/java/io/treehouses/remote/MainApplication.java
- app/src/main/java/io/treehouses/remote/bases/BaseHomeFragment.java
> home: rating added (fixes #589)

- app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.java
- app/src/main/java/io/treehouses/remote/adapter/ServicesListAdapter.java
- app/src/main/res/layout/services_row_layout.xml
- Links highlighted and ready to click
- The info generated on click of the info button
- Since the info may come in different lines, string concatenate until the number of quotations marks in the output is equal to 2. Then Output the string.
> services: info added (fixes #626)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
Wait for a response from `treehouses default network ` before switching network profiles.
> home: wait for response with profile action (fixes #634)

- app/src/main/java/io/treehouses/remote/Fragments/NetworkFragment.java
Solution: Check if string is long enough to index
> Network: string out of bounds (fixes #644)

- app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.java
- app/src/main/java/io/treehouses/remote/bases/BaseServicesFragment.java
- app/src/main/res/layout/dialog_choose_url.xml
- Add a picker for a browser for the local urls
- A dialog to choose between tor and local browser
- If a tor browser is not installed, tell the user to install it from Play Store
> services: local or tor url (fixes #608)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
- app/src/main/java/io/treehouses/remote/bases/BaseHomeFragment.java
- Checks if the APK version meets the minimum version required for Treehouses CLI.
> home: check minimal apk version with cli (fixes #649)

- app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.java
- app/src/main/java/io/treehouses/remote/bases/BaseServicesFragment.java
For new services CLI update: https://github.com/treehouses/cli/pull/693 
- Changed the command sent from "up" to "install" and "start" to "up"
> services: switch up and install (fixes #647)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
- app/src/main/java/io/treehouses/remote/adapter/ProfilesListAdapter.java
- Add the default network profile
> home: add default network to profiles (fixes #641)

- app/src/main/java/io/treehouses/remote/bases/BaseHomeFragment.java
- app/src/main/res/xml/app_preferences.xml
> settings: share data switch (fixes #676)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
- app/src/main/java/io/treehouses/remote/bases/BaseHomeFragment.java
- app/src/main/res/layout/activity_home_fragment.xml
- Added internet status to home fragment
- Add to every screen the internet status
> home: internet status (fixes #686)

- app/src/main/java/io/treehouses/remote/Fragments/ServicesDetailsFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/ServicesFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/SimpleFragmentPagerAdapter.java
- app/src/main/java/io/treehouses/remote/adapter/ServicesListAdapter.java
- app/src/main/java/io/treehouses/remote/callback/ServicesListener.java
- app/src/main/res/layout/activity_services_details.xml
- app/src/main/res/layout/activity_services_fragment.xml
- app/src/main/res/layout/activity_services_tab_fragment.xml
- OnClick of service in Overview sends to the details page
- GUI improvements
- Material Design
- Autorun
- Restart button
- PageAdapter on the Details Page
> services: redesign 2nd

- app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.java
> status: upgrade refresh (fixes #576)(fixes #692)

- app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.java
- app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.java
- app/src/main/res/values/strings.xml
- Autocomplete commands taken straight from Raspberry Pi instead of hardcoded values
- When an item is selected, a space is added, and then next level of commands is shown
- Better functionality
> terminal: autocomplete improvements (fixes #623)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
https://github.com/treehouses/cli/pull/1017 
Reduce errors in Bluetooth carryover
> home: treehouses remote version

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
Check for the size of the array before loading
> home: network profiles indexoutofbounds (fixes #705)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
Check for null ptr, and moved the `notificationListener` to top of `readMessage` function
> home: no null pointer (fixes #702)

- app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.java
- app/src/main/res/drawable/custom_progress_bar.xml
- app/src/main/res/layout/activity_services_details.xml
- app/src/main/res/layout/activity_services_tab_fragment.xml
- app/src/main/res/values/styles.xml
- displays how much memory has been used (Roughly)
- Animation on load
> services: memory usage overview (fixes #699)

- app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/TunnelFragment.java
- app/src/main/java/io/treehouses/remote/InitialActivity.java
- app/src/main/java/io/treehouses/remote/Network/BluetoothChatService.java
- app/src/main/res/xml/app_preferences.xml
Ready for tests. It is the phoenix.
> bluetooth automatic reconnect (fixes #713)

- app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.java
- app/src/main/java/io/treehouses/remote/Network/BluetoothChatService.java
- app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.java
- app/src/main/java/io/treehouses/remote/pojo/CommandsList.java
- More reliable (less errors with reading in)
- Less strain on Bluetooth
- No overflow commands from other activities shown
> terminal: use json commands list (fixes #719)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
- app/src/main/java/io/treehouses/remote/bases/BaseHomeFragment.java
Used `treehouses remote check`
> home: treehouses remote check (fixes #717)

- app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.java
- app/src/main/java/io/treehouses/remote/Network/ParseDbService.java
- app/src/main/java/io/treehouses/remote/utils/Utils.java
Removed the request for device serial number for user logs
Will show up as undefined on parse DB
> home: no serial number (fixes #756)

- app/src/main/res/layout/fragment_about.xml
> about: refactor (fixes #763)

- app/src/main/res/layout/activity_terminal_fragment.xml
Fixes #776 
- Added constraint to top
> terminal: listview (fixes #776)

- app/src/main/java/io/treehouses/remote/Fragments/SystemFragment.java
- app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderSSHKey.java
- app/src/main/java/io/treehouses/remote/pojo/NetworkListItem.java
- app/src/main/res/layout/configure_ssh_key.xml
ssh-keygen
use new centralize bluetooth string
> system: add sshkey (fixes #774)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
- app/src/main/java/io/treehouses/remote/utils/CommandManager.kt
- app/src/main/res/values/commands.xml
> home: refactor to centralized (fixes #778)

- app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderCamera.java
- app/src/main/java/io/treehouses/remote/pojo/NetworkListItem.java
- app/src/main/res/layout/configure_camera.xml
> system: toggle camera (fixes #783)

- app/src/main/res/xml/app_preferences.xml
> home: heavy metal is default (fixes #796)

- app/src/main/java/io/treehouses/remote/Fragments/NewNetworkFragment.kt
Fixes #798 
"Network Mode updated" to "Network Mode retrieved"
> network: network retrieved (fixes #798)

- app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/HotspotBottomSheet.kt
- app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/WifiBottomSheet.kt
- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
- app/src/main/java/io/treehouses/remote/pojo/NetworkProfile.java
- app/src/main/java/io/treehouses/remote/utils/SaveUtils.java
- app/src/main/res/layout/dialog_hotspot.xml
- Added property isHidden to network profiles
> home: add hidden wifi/hotspot profiles (fixes #841)

- app/src/main/java/io/treehouses/remote/bases/BaseServicesFragment.java
For `constructServicesList`,  it seems that while fixing 2 CodeClimate issues, cognitive complexity of 11 and duplicate code blocks, one new issue (cognitive complexity of 6) arose.
Whatever I try to do, I either fully fix duplicate code blocks or fully fix cognitive complexity. Does anyone have some suggestion on what could be changed here or should we just stick to a cognitive complexity of 6 for now (better than 11 at least)?
The performAction changes should be good to go.
> refactor BaseServicesFragment

- app/src/main/res/layout/dialog_bridge.xml
- app/src/main/res/layout/dialog_ethernet.xml
- app/src/main/res/layout/dialog_hotspot.xml
- app/src/main/res/layout/dialog_wifi.xml
> network: white text on bottom sheet fix (fixes #840)

- app/src/main/java/io/treehouses/remote/Fragments/SettingsFragment.kt
- app/src/main/java/io/treehouses/remote/SplashScreenActivity.kt
- app/src/main/res/values-night/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/app_preferences.xml
> settings: dark mode set to automatic as default (fixes #845)

- app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/WifiBottomSheet.kt
- app/src/main/res/layout/dialog_wifi.xml
- app/src/main/res/values-night/commands.xml
- app/src/main/res/values/commands.xml
Added the enterprise command to the wifi dialog (Username field disappears when enterprise is unselected)
> network: wpa2 enterprise wifi added (fixes #848)

- app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/AddCommandDialogFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/ChPasswordDialogFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
- app/src/main/java/io/treehouses/remote/Fragments/NewNetworkFragment.kt
- app/src/main/java/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
- app/src/main/java/io/treehouses/remote/Fragments/ServicesFragment.java
- app/src/main/java/io/treehouses/remote/Fragments/SettingsFragment.kt
- app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.kt
- app/src/main/java/io/treehouses/remote/InitialActivity.kt
- app/src/main/java/io/treehouses/remote/adapter/ProfilesListAdapter.java
- app/src/main/java/io/treehouses/remote/adapter/ViewHolderTether.java
- app/src/main/java/io/treehouses/remote/bases/BaseHomeFragment.kt
- app/src/main/java/io/treehouses/remote/bases/BaseServicesFragment.java
- app/src/main/java/io/treehouses/remote/bases/PermissionActivity.kt
- app/src/main/java/io/treehouses/remote/utils/GPSService.java
- app/src/main/res/layout/chpass_dialog.xml
- app/src/main/res/layout/dialog_add_command.xml
- app/src/main/res/layout/dialog_bridge.xml
- app/src/main/res/layout/dialog_ethernet.xml
- app/src/main/res/layout/dialog_hotspot.xml
- app/src/main/res/layout/dialog_rename_status.xml
- app/src/main/res/layout/dialog_wifi.xml
- app/src/main/res/values-night/styles.xml
- app/src/main/res/values/styles.xml
fixes #852
Please test and merge first (avoid merge conflict)
> dark mode in refactored AlertDialog's (fixes #852)

- app/src/main/res/layout/activity_splash_screen.xml
> splash: dark mode (fixes #886)

- app/build.gradle
- app/src/main/java/io/treehouses/remote/Fragments/ServiceCardFragment.kt
- app/src/main/java/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
> services: no page crash (fixes #894)

- app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.java
- app/src/main/res/layout/activity_services_tab_fragment.xml
> services: add memory percentage (fixes #706)

- app/src/main/res/layout/dialog_tor_ports.xml
fixes #922 
See the issue and check if the problem is resolved with this
> tunnel: add tor dialog no white text (fixes #922)

- app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
Update the boolean check (check if false not true)
> home: check for test connection dialog (fixes #914)

- app/src/main/java/io/treehouses/remote/Fragments/ServicesFragment.kt
- app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.kt
> services: oops (fixes #942)

- app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.kt
> system: wificountry oops (fixes #948)

- app/src/main/java/io/treehouses/remote/adapter/NetworkListAdapter.kt
fixes master issue (did not build due to mismatched parameters in System Fragment (NetworkListAdapter.kt))
> system: oops (fixes #952)

- app/src/main/res/layout/new_network.xml
> fixes networkmode text colour

- app/src/main/java/io/treehouses/remote/utils/CommandManager.kt
- Alert dialog does not show anymore (improved the error checking)
> services: update cli handling (fixes #900)

- app/src/main/java/io/treehouses/remote/Fragments/ServiceCardFragment.kt
- app/src/main/java/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
- app/src/main/java/io/treehouses/remote/Fragments/ServicesFragment.kt
- app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.kt
- app/src/main/java/io/treehouses/remote/adapter/ServiceCardAdapter.java
- app/src/main/java/io/treehouses/remote/adapter/ServicesListAdapter.kt
- app/src/main/java/io/treehouses/remote/bases/BaseServicesFragment.kt
- app/src/main/java/io/treehouses/remote/pojo/ServiceInfo.kt
> cleaning up switch to dark mode (fixes #960) (fixes #801)

- app/src/main/res/values-night/styles.xml
- app/src/main/res/values/styles.xml
**Options Menu** should have correct colors in both modes and everything else should be unchanged.
> options: dark mode

- app/src/main/java/io/treehouses/remote/Tutorials.kt
Fixes #931 
- Remember to clear app data when testing a fragment multiple times
> services: tutorial (fixes #931)

- app/src/main/res/layout/configure_ssh_key.xml
- app/src/main/res/layout/layout_btn_configuration.xml
> system: white button text color (fixes #979)

- app/src/main/res/drawable/ic_about_btn.xml
- app/src/main/res/drawable/ic_give_feedback.xml
- app/src/main/res/layout/fragment_about.xml
> about: rounded buttons

- app/src/main/java/io/treehouses/remote/Fragments/AboutFragment.kt
Extracted methods to fix code smell and improve readability
> about: refactor (fixes #973)

- app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.kt
- app/src/main/res/layout/activity_status_fragment.xml
fixes #976
Temperature in Status Fragment
> status: temperature added (fixes #976)

- app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.kt
- app/src/main/res/color/status_upgrade_button.xml
- app/src/main/res/layout/activity_status_fragment.xml
Upgrade button is **disabled** when unusable
> status: disabled button when no update (fixes #723)

- app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.kt
- app/src/main/res/color/status_upgrade_button.xml
- app/src/main/res/layout/activity_status_fragment.xml
fixes #1038
Removed connection status header
> status: remove header (fixes #1038)

- app/src/main/java/io/treehouses/remote/utils/GPSService.kt
> refactor GPSService.kt (fixes #1034)

- app/src/main/java/io/treehouses/remote/adapter/ProfilesListAdapter.java
- app/src/main/res/drawable/expandlist_foreground.xml
- app/src/main/res/layout/list_group.xml
- app/src/main/res/layout/row_profile.xml
- app/src/main/res/values-night/color.xml
- app/src/main/res/values/color.xml
> home: dark mode for network profiles list (fixes #1027)

- app/src/main/res/layout/service_card.xml
> services: normed icon size and background (fixes #1058)

- app/src/main/res/layout/dialog_tor_ports.xml
> tunnel: number keyboard (fixes #1011)

- app/src/main/res/layout/activity_tor_fragment.xml
> tunnel: tor constraints (fixes #1010)

- app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.kt
- app/src/main/res/values-night/color.xml
- app/src/main/res/values/color.xml
> terminal: white text for dark mode (fixes #1048)

- app/src/main/java/io/treehouses/remote/Fragments/ServicesFragment.kt
fixes #1060
Testing:
Check several times to see if the bug is gone, even without the fix the bug takes several tries to recreate so testing if it's fixed or not will be difficult.
> services: switch to settings without oops (fixes #1060)

- app/src/main/java/io/treehouses/remote/InitialActivity.kt
> status: icon fix (fixes #1040)

- app/src/main/res/values-night/styles.xml
- app/src/main/res/values/styles.xml
> settings: dialog popups dark mode (fixes #1029)

- .gitlab-ci.yml
Fixes #992 
The mistake I had last time was using `-z` instead of `-n`, oops!
> update .gitlab-ci.yml (fixes #992)

- app/src/main/java/io/treehouses/remote/Fragments/TorTabFragment.kt
- app/src/main/res/layout/activity_tor_fragment.xml
- app/src/main/res/layout/select_dialog_item.xml
> tunnel: tor port list dark mode (fixes #1028)

- app/src/main/res/drawable/icon_back.xml
- app/src/main/res/layout/service_card.xml
> services: rounded icons in dark mode (fixes #1066)

- app/src/main/java/io/treehouses/remote/Fragments/TorTabFragment.kt
Fixes #1050
Dependent on https://github.com/treehouses/cli/pull/1620. 
Run ` treehouses upgrade cli no-tor-ports` to test.
> tunnel: delete last tor port (fixes #1050)

- app/src/main/res/drawable-anydpi/back_button.xml
- app/src/main/res/layout/dialog_help.xml
- app/src/main/res/layout/row_help.xml
- app/src/main/res/values-night/color.xml
- app/src/main/res/values-night/styles.xml
- app/src/main/res/values/color.xml
- app/src/main/res/values/styles.xml
> terminal: dark help list (fixes #1078)

- app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.kt
- app/src/main/res/layout/simple_dropdown_item_1line.xml
> terminal: dark autocomplete list (fixes #1080)

- app/src/main/java/io/treehouses/remote/Tutorials.kt
> tutorial: refactor (fixes #1070)

- app/src/main/java/io/treehouses/remote/bases/BaseServicesFragment.kt
> services: headers (fixes #1095)

- app/src/main/java/io/treehouses/remote/Fragments/TorTabFragment.kt
- app/src/main/res/layout/activity_tor_fragment.xml
> tunnel: tor notify now button

- app/src/main/java/io/treehouses/remote/Fragments/ServicesFragment.kt
- app/src/main/java/io/treehouses/remote/utils/SaveUtils.kt
> services: refactor save utils (fixes #1099)

- app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
> services: no empty toast (fixes #1086)

- app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
> network: tutorial added (fixes #932)

- app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
> status: new tutorial (fixes #1116)

- app/src/main/res/xml/app_preferences.xml
> settings: reactivate tutorials (fixes #1117)

- app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
- build.gradle
> status: hide button once upgrading (fixes #1103)

- app/src/main/res/values-night/strings.xml
> all: sync night strings (fixes #1125)

- app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesFragment.kt
> services: successful refresh (fixes #1135)

- app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
Fixes #1107 
1. Go to tunnel.
2. Add a port.
3. Check to see entry fields are cleared from previous entry.
> tunnel: clear tor port (fixes #1107)

- app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalView.kt
Also deleted two unused functions
> refactor TerminalView

- app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConfig.kt
- app/src/main/kotlin/io/treehouses/remote/bases/BaseFragment.kt
> refactor SSHConfig (fixes #1169)

- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/EditHostDialog.kt
- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHAllKeys.kt
- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHKeyGen.kt
- app/src/main/res/layout/dialog_view_keys.xml
- app/src/main/res/layout/edit_host.xml
- app/src/main/res/layout/key_type_spinner_item.xml
- app/src/main/res/layout/keys_dialog.xml
> ssh: sshkey dark mode (fixes #1163)

- app/build.gradle
- app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConfig.kt
- app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalManager.kt
- app/src/main/kotlin/io/treehouses/remote/SSHConsole.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHRow.kt
- app/src/main/res/layout/dialog_ssh.xml
- app/src/main/res/layout/row_ssh.xml
When pressing back from SSHConsole, the connection is still alive. Show this in the connected hosts section.
> ssh: show connection status (#1184)

- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderWifiCountry.kt
- app/src/main/res/layout/configure_wificountry.xml
- app/src/main/res/layout/dialog_wificountry.xml
- app/src/main/res/layout/select_dialog_item_countries.xml
> system: improve wificountry (fixes #1143)

- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/EditHostDialog.kt
- app/src/main/kotlin/io/treehouses/remote/SSH/beans/HostBean.kt
- app/src/main/kotlin/io/treehouses/remote/utils/SaveUtils.kt
- Check if hostname is in list rather than the object HostBean (since the equals method contained font size)
> ssh: no duplicate hosts (fixes #1164)

- app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
The code I commented out is not used
> tutorial: no duplication

- app/src/main/kotlin/io/treehouses/remote/SSH/Encryptor.kt
> refactor Encryptor (fixes #1182)

- app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesFragment.kt
> services: caching refresh (fixes #1180)

- app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
> tunnel: tor add ports keyboard focus (fixes #1188)

- app/src/main/res/layout/dialog_ssh.xml
> ssh: update connect dialog

- app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
> tunnel: no duplicate sshtunnel host (fixes #1213)

- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHKeyGen.kt
- app/src/main/res/layout/keys_dialog.xml
Testing:
- Try an empty key name
- Try a key name that already exists
> ssh: no duplicate keys (fixes #1203)

- app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesFragment.kt
> services: no duplication (fixes #1204) (fixes #1207)

- app/proguard-rules.pro
- app/src/main/kotlin/io/treehouses/remote/Fragments/ServiceCardFragment.kt
- app/src/main/kotlin/io/treehouses/remote/bases/BaseServicesFragment.kt
- app/src/main/kotlin/io/treehouses/remote/pojo/ServiceInfo.kt
- app/src/main/kotlin/io/treehouses/remote/pojo/ServicesData.kt
- app/src/main/res/layout/service_card.xml
Can be found under `services`: details
How to test:
- Hold the treehouses remote application icon on your phone
- Tap on app info
- Tap on clear data on the bottom drawer
- Run the app
- Go to `services` fragment
- Select a service
**Make sure each service shows size**
> services: show size in detail view (fixes #1105)

- app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalKeyListener.kt
In the future, we will have to break down the class to seperate files if we want to appease code climate. For now, the total debt should be a lot lower.
> refactor TerminalKeyListener

- app/src/main/res/layout/new_network.xml
> network: scroll (fixes #1221)

- app/build.gradle
- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHKeyGen.kt
- app/src/main/res/layout/keys_dialog.xml
- app/src/main/res/values/strings.xml
> ssh: variable bit size of sshkeys (fixes #1224)

- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderBlocker.kt
Reduces Maintainability: 6 Hours
> refactor ViewHolderBlocker

- app/src/main/res/drawable/custom_pref_bottom.xml
- app/src/main/res/drawable/custom_pref_middle.xml
- app/src/main/res/drawable/custom_pref_top.xml
- app/src/main/res/drawable/custom_pref_whole.xml
- app/src/main/res/layout/custom_pref_bottom.xml
- app/src/main/res/layout/custom_pref_category.xml
- app/src/main/res/layout/custom_pref_middle.xml
- app/src/main/res/layout/custom_pref_top.xml
- app/src/main/res/layout/custom_pref_whole.xml
- app/src/main/res/values-night/color.xml
- app/src/main/res/values/color.xml
- app/src/main/res/xml/app_preferences.xml
> settings: redesign

- app/src/main/kotlin/io/treehouses/remote/bases/BaseFragment.kt
> home: no crashes (fixes #1244)

- app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
> home: no initial activity crash (fixes #1242)

- app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
- app/src/main/res/values/commands.xml
Reduces Maintainability: 5 Hours
> refactor TunnelSSHFragment

- app/src/main/kotlin/io/treehouses/remote/Fragments/CommunityFragment.kt
- app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
- app/src/main/kotlin/io/treehouses/remote/callback/BackPressReceiver.kt
- app/src/main/res/layout/fragment_community.xml
- app/src/main/res/menu/initial.xml
- app/src/main/res/values/strings.xml
- Added Treehouses map in Community in Options Menu
> options: treehouses map (fixes #1253)

- app/src/main/res/layout/activity_tor_fragment.xml
> tunnel: tor logo re-added (fixes #1240)

- app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesFragment.kt
> services: tutorial improvement (fixes #1255)

- app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
inform first time user to add port
> tunnel: add info for first time user (fixes #1267)

- app/src/main/res/layout-notlong/activity_home_fragment.xml
fixes #1138
On a device, with less screen height the screen will be scrollable
> home: scroll for some devices (fixes #1138)

- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/EditHostDialog.kt
- app/src/main/kotlin/io/treehouses/remote/utils/SaveUtils.kt
- app/src/main/res/layout/edit_host.xml
Fixes #1212 
1. Go to SSH(Beta).
2. Add a host if you don't have one already by entering a host and using the connect button.
3. Choose a host and click on the pencil icon to edit.
4. There should be a delete icon on the top right.
5. You can click on it to delete the host and upon a refresh the host should disappear.
Also which one do you prefer?
The current one
Or this one
> ssh: delete previous host (fixes #1212)

- app/src/main/res/drawable/ic_blue.xml
- app/src/main/res/drawable/ic_grey.xml
- app/src/main/res/layout/dialog_bridge.xml
- app/src/main/res/layout/dialog_ethernet.xml
- app/src/main/res/layout/dialog_hotspot.xml
- app/src/main/res/layout/dialog_wifi.xml
> all: rounded buttons in bottom sheet dialogs

- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/HelpDialog.kt
- app/src/main/res/drawable/ic_feedback_back.xml
- app/src/main/res/layout/dialog_help.xml
> terminal: help dialog design update

- app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConfig.kt
- app/src/main/kotlin/io/treehouses/remote/SSH/SSH.kt
- app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalManager.kt
- app/src/main/kotlin/io/treehouses/remote/SSHConsole.kt
> refactor TerminalManager.kt

- app/src/main/kotlin/io/treehouses/remote/bases/BaseServicesFragment.kt
> services: no crashes (fixes #1296)

- app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
- app/src/main/kotlin/io/treehouses/remote/utils/SaveUtils.kt
Fixes [#1292](https://github.com/treehouses/remote/issues/1292) and [#1295](https://github.com/treehouses/remote/issues/1295)
> options: fragment title (fixes #1292) (fixes #1295)

- app/src/main/kotlin/io/treehouses/remote/Fragments/SettingsFragment.kt
- app/src/main/kotlin/io/treehouses/remote/utils/SaveUtils.kt
- app/src/main/res/xml/app_preferences.xml
> settings: clear services cache (fixes #1289)

- app/src/main/kotlin/io/treehouses/remote/Fragments/DiscoverFragment.kt
- app/src/main/res/layout/activity_discover_fragment.xml
> system: dark mode for discover (fixes #1305)

- app/src/main/kotlin/io/treehouses/remote/Fragments/HomeFragment.kt
- app/src/main/res/layout/activity_home_fragment.xml
> home: bottom button redesign (fixes #1313)

- app/src/main/res/layout/configure_discover.xml
- app/src/main/res/values/strings.xml
> system: improved discover link visibility (fixes #1310)

- app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
- app/src/main/kotlin/io/treehouses/remote/pojo/StatusData.kt
- app/src/main/res/drawable/blue_progress_bar.xml
- app/src/main/res/layout/activity_status_fragment.xml
> status: storage bar added (fixes #1307)

- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/DeleteSSHKey.kt
- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHAllKeys.kt
Fixes #1303 
1. Generate key(s).
2. Click on view all keys and delete keys.
3. They should now be deleted instantly.
> ssh: sshkeys instant view refresh (fixes #1303)

- app/src/main/kotlin/io/treehouses/remote/Fragments/SystemFragment.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderVnc.kt
> system: vnc switch detection (fixes #1343)

- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.kt
- app/src/main/res/layout/dialog_listview.xml
- app/src/main/res/layout/simple_list_item.xml
> network: wifi dialog dark mode (fixes #1347)

- app/src/main/kotlin/io/treehouses/remote/SSH/PromptHelper.kt
> refactor PromptHelper

- app/src/main/kotlin/io/treehouses/remote/IntroActivity.kt
> refactor IntroActivity

- app/src/main/kotlin/io/treehouses/remote/Fragments/ShowBluetoothFile.kt
> refactor ShowBluetoothFile

- app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
> tunnel: no ssh crashes (fixes #1373)

- app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
> tunnel: ssh ports list (fixes #1379)

- app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
- app/src/main/res/layout/activity_tunnel_ssh_fragment.xml
- app/src/main/res/layout/dialog_sshtunnel_hosts.xml
- app/src/main/res/layout/dialog_sshtunnel_ports.xml
> tunnel: ssh redesign (fixes #1389)

- Vagrantfile
Fixes #1377 
Install codeclimate-wrapper on `vagrant up`
> update Vagrantfile (fixes #1377)

- app/src/main/res/layout/dialog_ethernet.xml
- app/src/main/res/layout/dialog_hotspot.xml
- app/src/main/res/layout/dialog_wifi.xml
> network: bottom sheet rounded dark mode (fixes #1403)

- app/src/main/res/layout/activity_tunnel_ssh_fragment.xml
> tunnel: ssh ui (fixes #1423)

- app/src/main/kotlin/io/treehouses/remote/Fragments/PreferenceFragments/UserCustomizationPreference.kt
> settings: toasts for SSH clearing (fixes #1415) (fixes #1416)

- app/src/main/res/values/commands.xml
> status: remove double dash in upgrade check (fixes #1440)

- app/src/main/res/drawable-v21/custom_pref_bottom.xml
- app/src/main/res/drawable-v21/custom_pref_middle.xml
- app/src/main/res/drawable-v21/custom_pref_top.xml
- app/src/main/res/drawable-v21/custom_pref_whole.xml
Fixes #1358 
1. Go to settings.
2. Click on any preference.
3. They should now all have a ripple effect when pressed.
> settings: visual feedback (fixes #1358)

- app/src/main/res/xml/user_customization_preferences.xml
> settings: round boxes (fixes #1461)

- app/src/main/res/layout/new_network.xml
> network: discover beta text (fixes #1481)

- app/src/main/res/layout/dialog_sshtunnel_key.xml
> tunnel: ssh beta added in keys title (fixes #1479)

- app/build.gradle
- app/release/output-metadata.json
- app/src/main/kotlin/io/treehouses/remote/Fragments/ShowBluetoothFile.kt
- app/src/main/res/layout/code_view.xml
- app/src/main/res/layout/fragment_show_bluetooth_file.xml
fixes #1393
fixes #1499 
- Remove codeView and used TextView instead
- Stops ANR errors
- Decreases app size by 800kB
> settings: show bluetooth script refactor (fixes #1393, #1499)

- app/src/main/kotlin/io/treehouses/remote/Fragments/PreferenceFragments/GeneralPreference.kt
- app/src/main/kotlin/io/treehouses/remote/Fragments/ServiceCardFragment.kt
- app/src/main/kotlin/io/treehouses/remote/Views/ServiceViewPager.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ServiceCardAdapter.kt
- app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesDetailsFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesOverviewFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesViewModel.kt
- app/src/main/kotlin/io/treehouses/remote/utils/ServiceHelper.kt
- app/src/main/res/layout/activity_services_fragment.xml
fixes #1493
fixes #1494 
- Documented code
- Fixed CodeClimate issues
- Fixed autorun issue when switching services
- Fixed the Service Clear Cache command
- Add progress bar at the top whenever fetching from server
> services: improvements and cleaning up (fixes #1493, #1494)

- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderTether.kt
- app/src/main/kotlin/io/treehouses/remote/pojo/NetworkListItem.kt
- app/src/main/res/drawable/ic_green2.xml
- app/src/main/res/layout/configure_tethering.xml
> system: tethering redesign (fixes #1485)

- README.md
fixes #1383 
* Makes the README more up to date with the newest technology
* Tutorial is clearer and more accurate
> update README.md (fixes #1383) 

- app/src/main/AndroidManifest.xml
removed manifest intent filters
> all: remove unneeded intent filters (fixes #1475)

- .travis.yml
> update travis.yml (fixes #1512)

- app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
- app/src/main/kotlin/io/treehouses/remote/bases/BaseStatusFragment.kt
- app/src/main/kotlin/io/treehouses/remote/pojo/StatusData.kt
- Was not entering correct if statement branch (Line 53 in BaseStatusFragment) `fun receiveMessage(readMessage: String){`.
- (The new json string contained the country= signature)
> status: ready for new json (fixes #1528)

- app/src/main/kotlin/io/treehouses/remote/Fragments/SystemFragment.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderTether.kt
> system: no crashes in open vnc (fixes #1530, #1532)

- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderCamera.kt
- app/src/main/res/layout/configure_camera.xml
Fixes #1531
1. Go to system.
2. Go to toggle camera.
3. Turn the camera on and off. The icon should update accordingly.
> system: toggle camera redesign (fixes #1531)

- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHAllKeys.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHAllKeyRow.kt
- app/src/main/kotlin/io/treehouses/remote/callback/KeyMenuListener.kt
- app/src/main/res/menu/keys_menu.xml
- app/src/main/res/values/commands.xml
> ssh: easy access for send key to server (fixes #1539)

- app/src/main/res/layout/configure_ssh_key.xml
Fixes #1526 
1. Go to system.
2. Go to add ssh key.
> system: add ssh key redesign (fixes #1526)

- app/src/main/res/layout/layout_btn_configuration.xml
- app/src/main/res/layout/open_vnc.xml
Fixes #1524 
1. Go to systems.
2. Go to Open VNC.
> system: open vnc redesign (fixes #1524)

- app/src/main/kotlin/io/treehouses/remote/bases/BaseStatusFragment.kt
> status: refresh after upgrade reactivated (fixes #1550)

- app/src/main/kotlin/io/treehouses/remote/Fragments/AboutFragment.kt
- app/src/main/res/drawable/ic_about_btn.xml
- app/src/main/res/drawable/ic_about_btn_pressed.xml
fixes #1396 
Changes button color when buttons in the about page are clicked; toggles between light and dark.
> about: button visual feedback when clicked (fixes #1396)

- app/src/main/res/layout/configure_ssh2fa.xml
Fixes #1545 
Fixes #1547 
1. Go to system.
2. Go to `SSH 2 Factor Authentication`
> system: ssh 2fa redesign (fixes #1545, #1547)

- app/src/main/res/drawable-anydpi/navigation_menu_bg.xml
> menu: visual feedback when selected (fixes #1560)

- app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
- app/src/main/res/layout/dialog_sshtunnel_key.xml
Fixes #1546 
1. Go to tunnel.
2. Go to SSH.
3. Click on the key icon and click on the `x` icon.
> tunnel: add ssh key dialog close button (fixes #1546)

- app/src/main/res/layout/service_card.xml
> services: scroll on service card when necessary (fixes #1556)

- app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
> network: tutorial for discover button (fixes #1486)

- app/src/main/AndroidManifest.xml
> all: remove backup permission (fixes #1520)

- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/AddCommandDialogFragment.kt
- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.kt
- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.kt
- app/src/main/kotlin/io/treehouses/remote/Fragments/SystemFragment.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderShutdownReboot.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderTether.kt
- app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
- app/src/main/kotlin/io/treehouses/remote/utils/DialogUtils.kt
Fixes #1551
Fixes #1583
1. Go to system
2. Go to `shutdown and reboot`.
3. Test out reboot.
4. Test out Shutdown.
> system: add confirmations (fixes #1551, #1583)

- app/src/main/kotlin/io/treehouses/remote/SSH/PromptHelper.kt
- Make T reified to get access to class of T (Boolean class vs String class)
> ssh: make password input work again (fixes #1617)

- app/src/main/kotlin/io/treehouses/remote/SSH/PromptHelper.kt
- app/src/main/kotlin/io/treehouses/remote/SSH/SSH.kt
- app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalBridge.kt
- app/src/main/kotlin/io/treehouses/remote/bases/BaseSSH.kt
> ssh: make ssh host detection work again (fixes #1617)

- app/src/main/kotlin/io/treehouses/remote/ui/services/BaseServicesDetailsFragment.kt
- app/src/main/res/drawable/ic_purple.xml
- app/src/main/res/layout/dialog_choose_url.xml
Fixes #1468 
Fixes #1544
1. Go to services.
2. Click a service that is running.
3. Click open link.
> services: redesign open url dialog (fixes #1468, #1544)

- app/src/main/res/drawable/ic_give_feedback.xml
- app/src/main/res/drawable/ic_give_feedback_button_pressed.xml
> about: feedback button with visual feedback (fixes #1624)

- app/src/main/res/drawable/add_command_background.xml
Fixes #1637
1. Go to terminal.
2. Go to commands.
> terminal: roundify add command button (fixes #1637)

- app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHAllKeys.kt
- app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConfig.kt
- app/src/main/kotlin/io/treehouses/remote/bases/BaseSSHKeyGen.kt
- app/src/main/kotlin/io/treehouses/remote/utils/KeyUtils.kt
- app/src/main/res/drawable/green_ripple.xml
- app/src/main/res/layout/dialog_ssh.xml
Fixes #1607
Fixes #1608
Fixes #1635
> ssh: smart connect (fixes #1607, #1608, #1635)

- app/src/main/res/layout/dialog_add_profile.xml
> tunnel: rename socks profile entry fields (fixes #1651)

- app/src/main/kotlin/io/treehouses/remote/fragments/NetworkFragment.kt
- app/src/main/kotlin/io/treehouses/remote/utils/CommandManager.kt
- app/src/main/res/layout/activity_network_fragment.xml
fixes #1537 
Show IP Address in the Network page under the Network mode
> network: show ip address (fixes #1537)

- app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
- app/src/main/kotlin/io/treehouses/remote/fragments/ShowBluetoothFileFragment.kt
> settings: enable back for showBluetooth (fixes #1673)

- app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
Return back to old command, `treehouses internet`
> home: change back to treehouses internet

- app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
- app/src/main/kotlin/io/treehouses/remote/fragments/SSHConfigFragment.kt
- app/src/main/kotlin/io/treehouses/remote/utils/SaveUtils.kt
fixes #1677 
First time users have a tutorial for the ssh (beta) page
> ssh: tutorial added (fixes #1677)

- app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
- app/src/main/kotlin/io/treehouses/remote/fragments/SSHTunnelFragment.kt
- app/src/main/kotlin/io/treehouses/remote/fragments/TunnelSSHFragment.kt
fixes #1678 
Adds a tutorial in the SSH tab for tunnel for first time users
> tunnel: ssh tutorial added (fixes #1678)

- app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
fixes #1696 
Tutorial updated for new terminal layout
> terminal: tutorial updated (fixes #1696)

- app/src/main/kotlin/io/treehouses/remote/ui/status/StatusViewModel.kt
fixes #1695 
Checks for wifi country before cli upgrade in status
> status: wificountry before upgrade check (fixes #1695)

- app/src/main/kotlin/io/treehouses/remote/bases/BaseTunnelSSHFragment.kt
- app/src/main/kotlin/io/treehouses/remote/fragments/TunnelSSHFragment.kt
fixes #1698 
SSH Tunnel now shows the keys after previously not
> sshtunnel: shows sshkeys (fixes #1698)

- .github/workflows/android-build.yml
- .github/workflows/android-release.yml
- app/build.gradle
> switch github action to automagic (fixes #1719)

- app/src/main/kotlin/io/treehouses/remote/BaseInitialActivity.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/NetworkListAdapter.kt
- app/src/main/kotlin/io/treehouses/remote/ui/system/SystemFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/system/SystemViewModel.kt
- app/src/main/res/values/commands.xml
fixes #1760
Refactor systems page into mvvm format
> system: refactor to mvvm (fixes #1760)

- app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
- app/src/main/res/values/strings.xml
fixes #1741 
added more text in the info button, as well as highlighting the info button during the tutorial
> sshtunnel: info and tutorial improvement (fixes #1741)

- app/src/main/kotlin/io/treehouses/remote/ui/network/NetworkViewModel.kt
- app/src/main/kotlin/io/treehouses/remote/ui/network/bottomsheetdialogs/WifiBottomSheet.kt
fixes #1768
Minor MVVM refactor for Network Dialog
> network: dialog MVVM refactor (fixes #1768)

- app/src/main/kotlin/io/treehouses/remote/fragments/TunnelSSHFragment.kt
- app/src/main/res/values/strings.xml
fixes #1775
eliminated the white spaces that appear in the corner of the info dialog box while in dark mode
> sshtunnel: info dialog box (fixes #1775)

- app/src/main/res/layout/fragment_about.xml
fixes #1288
fix Give Feedback button so that it appears round
> about: button design (fixes #1288)

- app/src/main/kotlin/io/treehouses/remote/fragments/dialogfragments/RPIDialogFragment.kt
fixes #1797
update the hashset for RPI Mac Ranges
> detect pi by mac new range added (fixes #1797)

- .github/workflows/android-release.yml
> update `android-release.yml` message on success (fixes #1800)

- app/src/main/kotlin/io/treehouses/remote/views/RoundedListPreference.kt
- app/src/main/res/xml/general_preferences.xml
> settings: rounded dialogs (fixes #1470)(fixes #1471)

- app/src/main/kotlin/io/treehouses/remote/adapter/RPIListAdapter.kt
- app/src/main/kotlin/io/treehouses/remote/callback/DeviceDeleteListener.kt
- app/src/main/kotlin/io/treehouses/remote/fragments/dialogfragments/RPIDialogFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
- app/src/main/res/layout/list_rpi_item.xml
- app/src/main/res/values/strings.xml
fixes #1802
add button in rpi dialog that allows you to delete it
> home: delete button added (fixes #1802)

- app/src/main/kotlin/io/treehouses/remote/fragments/dialogfragments/RPIDialogFragment.kt
fixes #1806 
updated some of the mac address to be correct
> connect: fix mac address (fixes #1806) 

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> all: new versions (fixes #1810)

- app/build.gradle
- app/src/main/kotlin/io/treehouses/remote/fragments/dialogfragments/RPIDialogFragment.kt
> actions: no minify (fixes #1830)

- .github/workflows/android-release.yml
> actions: enable playstore upload (fixes #1858)

- app/src/main/AndroidManifest.xml
fixes #1861
this pr adds
`android:exported` attribute which controls accessibilty of services component
> actions: better `AndroidManifest` (fixes #1861)

- .github/workflows/android-release.yml
> actions: switch to `dogi/upload-release-action` (fixes #1886)

- .github/workflows/android-release.yml
> actions: better release (fixes #1888)

- app/src/main/kotlin/io/treehouses/remote/network/BluetoothChatService.kt
fixes #1878
this pr add bluetooth permission checks in BluetoothChatService
> actions: add bluetooth checks (fixes #1878)

- app/src/main/kotlin/io/treehouses/remote/network/BluetoothChatService.kt
> actions: better bluetooth (fixes #1878)

- app/src/main/AndroidManifest.xml
> actions: foreground bluetooth service (fixes #1919)

- app/src/main/kotlin/io/treehouses/remote/utils/ServiceHelper.kt
> services: better size strings (fixes #1895)

- .github/workflows/android-release.yml
- app/src/main/kotlin/io/treehouses/remote/fragments/SSHConfigFragment.kt
> ssh: survive empty ip (fixes #1910)

- app/src/main/kotlin/io/treehouses/remote/fragments/dialogfragments/RPIDialogFragment.kt
> connect: all bluetooth devices clickable (fixes #1937)

- app/src/main/kotlin/io/treehouses/remote/fragments/dialogfragments/RPIDialogFragment.kt
> connect: more mac addresses (fixes #1971)

- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHAllKeyRow.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHRow.kt
- app/src/main/kotlin/io/treehouses/remote/ssh/terminal/BaseTerminalView.kt
> all: code modernization (fixes #1966)

- app/src/main/kotlin/io/treehouses/remote/fragments/dialogfragments/RPIDialogFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
- app/src/main/kotlin/io/treehouses/remote/utils/DialogUtils.kt
- app/src/main/res/layout/dialog_progress.xml
fixes #1964
this pr replaces deprecated ProgressDialog with a customProgressDialog
https://github.com/treehouses/remote/assets/64019708/fa57b7d1-cc3b-4366-8137-24b799d48d16
> all: better progress dialog (fixes #1964)

- app/src/main/kotlin/io/treehouses/remote/BaseInitialActivity.kt
- app/src/main/kotlin/io/treehouses/remote/SplashScreenActivity.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderBlocker.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderCamera.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSH2FA.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHKey.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderShutdownReboot.kt
- app/src/main/kotlin/io/treehouses/remote/bases/BaseFragment.kt
- app/src/main/kotlin/io/treehouses/remote/bases/FragmentViewModel.kt
- app/src/main/kotlin/io/treehouses/remote/sshconsole/DerivedSSHConsole.kt
- app/src/main/kotlin/io/treehouses/remote/sshconsole/RootSSHConsole.kt
- app/src/main/kotlin/io/treehouses/remote/ui/system/SystemFragment.kt
> all: use `Handler`s with `Looper`s (fixes #1953)

- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
- app/src/main/kotlin/io/treehouses/remote/utils/GPSService.kt
> all: foreground location service (fixes #1988)

- app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
- app/src/main/kotlin/io/treehouses/remote/fragments/CommunityFragment.kt
- app/src/main/kotlin/io/treehouses/remote/utils/GPSService.kt
fixes #1992
https://github.com/treehouses/remote/assets/64019708/2355b914-b7b4-49e6-a4cb-1fbb36707e87
> all: foreground when location allowed (fixes #1992)

- app/src/main/kotlin/io/treehouses/remote/utils/GPSService.kt
> all: smoother foreground location (fixes #2006)

- app/src/main/kotlin/io/treehouses/remote/fragments/ServiceCardFragment.kt
fixes #1950
this pr implements a safer null handling
> services: smoother initialization (fixes #1950)

- app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt
> all: modern back press (fixes #2028)

- app/src/main/kotlin/io/treehouses/remote/BaseInitialActivity.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/CommandListAdapter.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/HelpAdapter.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ProfilesListAdapter.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/RPIListAdapter.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ServicesListAdapter.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/SystemListAdapter.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/TerminalPagerAdapter.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/TunnelPortAdapter.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderBlocker.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderCamera.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSH2FA.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHAllKeyRow.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHKey.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderShutdownReboot.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderTether.kt
- app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderVnc.kt
- app/src/main/kotlin/io/treehouses/remote/callback/HomeInteractListener.kt
- app/src/main/res/layout/configure_camera.xml
- app/src/main/res/layout/configure_ssh2fa.xml
- app/src/main/res/layout/open_vnc.xml
> all: smoother adapters (fixes #2012)

- app/src/main/kotlin/io/treehouses/remote/BaseInitialActivity.kt
> all: better bluetooth initialization (fixes #2032)

- app/src/main/kotlin/io/treehouses/remote/utils/GPSService.kt
> all: smoother location access (fixes #2037)

- app/src/main/kotlin/io/treehouses/remote/bases/BaseFragment.kt
> settings: stabler initialization (fixes #2031)

- app/src/main/kotlin/io/treehouses/remote/bases/FragmentViewModel.kt
- app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/home/HomeViewModel.kt
- app/src/main/kotlin/io/treehouses/remote/ui/network/BaseNetworkViewModel.kt
- app/src/main/kotlin/io/treehouses/remote/ui/network/NetworkFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/network/NetworkViewModel.kt
- app/src/main/kotlin/io/treehouses/remote/ui/network/bottomsheetdialogs/BridgeBottomSheet.kt
- app/src/main/kotlin/io/treehouses/remote/ui/network/bottomsheetdialogs/EthernetBottomSheet.kt
- app/src/main/kotlin/io/treehouses/remote/ui/network/bottomsheetdialogs/HotspotBottomSheet.kt
- app/src/main/kotlin/io/treehouses/remote/ui/network/bottomsheetdialogs/WifiBottomSheet.kt
- app/src/main/kotlin/io/treehouses/remote/ui/services/BaseServicesDetailsFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesDetailsFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesOverviewFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesViewModel.kt
- app/src/main/kotlin/io/treehouses/remote/ui/socks/SocksFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/socks/SocksViewModel.kt
- app/src/main/kotlin/io/treehouses/remote/ui/sshtunnel/BaseSSHTunnelFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/sshtunnel/BaseSSHTunnelViewModel.kt
- app/src/main/kotlin/io/treehouses/remote/ui/sshtunnel/SSHTunnelFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/sshtunnel/SSHTunnelViewModel.kt
- app/src/main/kotlin/io/treehouses/remote/ui/status/StatusFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/status/StatusViewModel.kt
- app/src/main/kotlin/io/treehouses/remote/ui/system/SystemFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/tor/TorFragment.kt
- app/src/main/kotlin/io/treehouses/remote/ui/tor/TorViewModel.kt
> all: smoother ui's (fixes #2030)

- app/src/main/kotlin/io/treehouses/remote/bases/BaseFragment.kt
issue #2042.
Reverting the changes made in #2040 seem to fix it for now.
> terminal: old but working initialization (fixes #2042)

- app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesViewModel.kt
> services: smoother view model (fixes #2053)

- app/src/main/kotlin/io/treehouses/remote/bases/BaseFragment.kt
> all: smoother bluetooth initialization (fixes #2057)

- .github/workflows/android-release.yml
fixes #2110 
put link between <> to avoid discord link preview taking too much space and cluttering the channel.
> actions: smoother discord notification (fixes #2110)

- app/build.gradle
> all: smoother dependencies (fixes #2127)

- app/src/main/kotlin/io/treehouses/remote/network/BluetoothChatService.kt
- app/src/main/kotlin/io/treehouses/remote/ui/home/HomeViewModel.kt
> all: smoother bluetooth (fixes #2134)

- app/src/main/kotlin/io/treehouses/remote/bases/BaseSSHConfig.kt
> ssh: smoother configuration (fixes #2047)

- app/src/main/kotlin/io/treehouses/remote/BaseInitialActivity.kt
> bluetooth: smoother initialization (fixes #2054)

- app/src/main/kotlin/io/treehouses/remote/bases/FragmentViewModel.kt
> bluetooth: smoother checks (fixes #2090)

- app/src/main/kotlin/io/treehouses/remote/fragments/dialogfragments/RPIDialogFragment.kt
fixes #2202
https://github.com/user-attachments/assets/18400481-5048-40fa-a640-33c5cdc5d506
> bluetooth: smoother discovery (fixes #2202)

- app/build.gradle
- build.gradle
> actions: bump `targetSdkVersion` to 35 (fixes #2208)
