treehouses/remote

app/build.gradle

When you update to 3.0.1 in the android studio it cause some gradle issues. Just needed to remove these lines.
Edit: Adding a little more info about what was fixed. If you update your android studio to the latest version, it would cause a gradel sync error if you freshly downloaded and synced it. Remove this line, it has caused the sync to pass without error.

fixing compatibility with 3.0.1

---

app/src/main/java/io/treehouses/remote/Fragments/SystemFragment.java

Fixes #470 
Updates the System Page Configure Tethering (beta) tab to only show the hotspot name instead of displaying the essid and wifi name.

system: only wifi for tether (fixes #470)

---

app/src/main/java/io/treehouses/remote/Constants.java
app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/AddCommandDialogFragment.java
app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/ChPasswordDialogFragment.java
app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.java
app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.java
app/src/main/java/io/treehouses/remote/MainApplication.java
app/src/main/java/io/treehouses/remote/adapter/CommandListAdapter.java
app/src/main/java/io/treehouses/remote/utils/SaveUtils.java
app/src/main/res/drawable/add_command_background.xml
app/src/main/res/drawable/ic_add_box_black_24dp.xml
app/src/main/res/layout/activity_terminal_fragment.xml
app/src/main/res/layout/dialog_add_command.xml
app/src/main/res/layout/list_add.xml
app/src/main/res/layout/list_item.xml
app/src/main/res/values/strings.xml

Added the ability to add custom commands to the dropdown menu in Terminal. Utilizes SharedPreferences to store an array of commands.
Ability to reset to default: Needs a settings screen for implementation

terminal: dynamically add commands (fixes #456)

---

app/src/main/java/io/treehouses/remote/Fragments/SettingsFragment.java
app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.java
app/src/main/java/io/treehouses/remote/utils/SaveUtils.java
app/src/main/res/xml/app_preferences.xml

Added "reset to default" and "clear commands list" to the settings screen. 
- Reset to default: Resets the commands list to the default values
- Clear Commands List: Makes commands list empty
Added the option to toggle autocomplete.
- Terminal Autocomplete: Turning it off disables autocomplete in the terminal

settings: add clear and default commands list (fixes #524)

---

app/src/main/java/io/treehouses/remote/Fragments/StatusFragment.java

#526 
Add a check to make sure string is long enough to index.
```
if (outs.get(3).length()>4) {
tvUpgrade.setText("Upgrade Status: Required for Version: " + outs.get(3).substring(4));
}
```

status: crashprevention with StringIndexError

---

app/src/main/java/io/treehouses/remote/utils/TextWatcherUtils.java

Add check for null.
```
if (editText != null && editable != null) {
return editable == editText.getEditableText() && !messageSent;
}
return false;
```

network: no null pointer crash (fixes #572)

---

app/build.gradle
app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
app/src/main/java/io/treehouses/remote/Fragments/SettingsFragment.java
app/src/main/java/io/treehouses/remote/adapter/ViewHolderBridge.java
app/src/main/java/io/treehouses/remote/adapter/ViewHolderHotspot.java
app/src/main/java/io/treehouses/remote/adapter/ViewHolderWifi.java
app/src/main/java/io/treehouses/remote/pojo/NetworkProfile.java
app/src/main/java/io/treehouses/remote/utils/SaveUtils.java
app/src/main/res/layout/dialog_bridge.xml
app/src/main/res/xml/app_preferences.xml

* Converted objects to JSON before storing in SharedPreferences to allow for greater adaptability
* Added `Clear Network Profiles` in Settings
* Implemented `Bridge` Function: Now available
* When no profiles are available, ask to go to Network Fragment to configure
* Show ProgressBar in AlertDialog with title "Connecting" instead of separate ProgressBar and Toast Message
* Individual Delete and Edit Profiles from HomeFragment

network: profiles with bridges (fixes #442)

---

app/src/main/java/io/treehouses/remote/Fragments/ServicesTabFragment.java

Changed the command run when clicking the start service button from`treehouses services planet up` to `treehouses services planet start`

services: start instead of up

---

app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java

- OnClick of the child was producing index out of bounds exception
- Added check to make sure size of lists are greater than 0 before indexing

home: handle empty profiles list (fixes #617)

---

app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java

Run `treehouses default network` before switching Network Profiles

home: profiles with treehouses default network (fixes #605)

---

app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.java

Add spaces after clicking a command from the autocomplete textview in the terminal.

terminal: add spaces to autocomplete textview (fixes #639)

---

app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.java
app/src/main/java/io/treehouses/remote/Fragments/TunnelFragment.java
app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.java

When the user presses the enter key on either the soft keyboard or the physical keyboard, the text is sent.
Done by checking if the last character of the string is a '\n'.

terminal: send text on newline (fixes #652)

---

app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java

Error:
```
java.lang.NullPointerException: 
at io.treehouses.remote.Fragments.HomeFragment.switchProfile (HomeFragment.java:116)
at io.treehouses.remote.Fragments.HomeFragment.readMessage (HomeFragment.java:293)
at io.treehouses.remote.Fragments.HomeFragment.access$500 (HomeFragment.java:49)
at io.treehouses.remote.Fragments.HomeFragment$4.handleMessage (HomeFragment.java:318)
at android.os.Handler.dispatchMessage (Handler.java:107)
at android.os.Looper.loop (Looper.java:214)
at android.app.ActivityThread.main (ActivityThread.java:7356)
at java.lang.reflect.Method.invoke (Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:930)
```
- Occurs when switching from Network Fragment to …

home: no null pointer in network profiles (fixes #663)

---

app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/BottomSheetDialogs/WifiBottomSheet.java

- Remove the overriding onDismiss() in WifiBottomSheetDialog

network: dismiss wifi dialog properly (fixes #660)

---

app/src/main/java/io/treehouses/remote/Fragments/SystemFragment.java

Error Given:
```
java.lang.NumberFormatException: 
at java.lang.Integer.parseInt (Integer.java:615)
at java.lang.Integer.parseInt (Integer.java:650)
at io.treehouses.remote.Fragments.SystemFragment.ipToLong (SystemFragment.java:131)
at io.treehouses.remote.Fragments.SystemFragment.convertIp (SystemFragment.java:119)
at io.treehouses.remote.Fragments.SystemFragment.checkSubnet (SystemFragment.java:109)
at io.treehouses.remote.Fragments.SystemFragment.checkAndPrefilIp (SystemFragment.java:77)
at io.treehouses.remote.Fragments.SystemFragment.access$200 (SystemFragment.java:33)
at io.treehouses.remote.Fragments.SystemFragment$1.handleMessage (SystemFragment.java:193)
at android.os.Handler.dispatchMessage (Handler.java:107)
at android.os.Looper.loop (Looper.java:214)
at …
```

system: numberformat (fixes #662)

---

app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.java
app/src/main/java/io/treehouses/remote/bases/BaseHomeFragment.java

- Show alert if the `treehouses remote version` returns an error (CLI is outdated)

home: remote version command check (fixes #656)

---

app/src/main/java/io/treehouses/remote/utils/VersionUtils.java

```
java.lang.NullPointerException: 
at io.treehouses.remote.utils.VersionUtils.getVersionCode (VersionUtils.java:10)
at io.treehouses.remote.Network.ParseDbService.sendLog (ParseDbService.java:23)
at io.treehouses.remote.bases.BaseHomeFragment.sendLog (BaseHomeFragment.java:112)
at io.treehouses.remote.bases.BaseHomeFragment.checkImageInfo (BaseHomeFragment.java:97)
at io.treehouses.remote.Fragments.HomeFragment.readMessage (HomeFragment.java:288)
at io.treehouses.remote.Fragments.HomeFragment.access$500 (HomeFragment.java:49)
at io.treehouses.remote.Fragments.HomeFragment$4.handleMessage (HomeFragment.java:323)
at android.os.Handler.dispatchMessage (Handler.java:107)
at android.os.Looper.loop (Looper.java:213)
at android.app.ActivityThread.main (ActivityThread.java:8147)
at …
```

home: no version code crash

---

app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/WifiDialogFragment.java

network: no leading space from search dialog (fixes #677)

---

app/src/main/java/io/treehouses/remote/Fragments/SettingsFragment.java

- Added dialog before clearing commands list, resetting commands list to d3efault, and before clearing network profiles.

settings: add alertdialog before clear/reset (fixes #618)

---

app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.java
app/src/main/java/io/treehouses/remote/Network/BluetoothChatService.java

- There is no need for the ability of an *insecure* Bluetooth connection. **Bluetooth 2.1** devices and above all require secure connections, and all versions of Raspberry Pi have a greater version than 2.1.
- The phone does *not need to accept* Bluetooth connections from other devices. The phone only needs to connect to the Raspberry Pi, and not receive connections.
`E/BluetoothChatService: Socket Type: Insecure accept() failedjava.io.IOException: read failed, socket might closed or timeout, read ret: -1`
This line was only being called if accepting a connection from another device. Since there was no need to look for incoming connections, the AcceptThread has been commented out.
- Commented out the AcceptThread
- Remove all code for insecure Bluetooth Connections
- In earlier versions, …

bluetooth stack refactor (fixes #548)

---

app/src/main/res/layout/fragment_about.xml

Fixes #508
Issues:
1) Left side 1st device (treehouses img) button text requires 10sp in order for text to fit.
2) The left 2 devices font size are referenced from the values/dimen, so making the 1st device font smaller will cause 2nd device (treehouses img) button text to be smaller.

about: redesign (fixes #508)

---

app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.java

1. Go to services
2. Before JSON response is received, switch to terminal
- GSON json to java class not successful (wrong JSON output received)
- Check if null, and if so, alert user

terminal: toast instead of overflow

---

app/src/main/java/io/treehouses/remote/bases/BaseServicesFragment.java

On rare occasions, when switching quickly between terminal and services, the wrong json getting received by the services fragment.
Similar to #747 , however, instead of guarding the terminal, this PR guards the services fragment.

services: catch null pointer on wrong json

---

app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt
app/src/main/java/io/treehouses/remote/MainApplication.kt
app/src/main/java/io/treehouses/remote/bases/BaseHomeFragment.kt

1. Logs were being sent onResume of Homefragment, causing block of logs per connection.
2. Strange outputs were caused by the overflow output from other fragments (namely Services Fragment). To reproduce strange logs, switch from Services Fragment back to the HomeFragment before the output has been received.
Added boolean to mainApplication to manage logsent state.

home: no strange logs (fixes #779)

---

app/src/main/java/io/treehouses/remote/bases/BaseBottomSheetDialog.java
app/src/main/res/values/styles.xml

Move the `bottomsheetdialog` up a bit; improves the ability to type. 
And user can move the bottom sheet dialog up if they wish to see more.

network: improve visibility of dialogs

---

app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt

Only change status if internetstatus drawable is available:
[Relevant Lines](https://github.com/treehouses/remote/compare/fix-home-null-ptr?expand=1#diff-6dceae3aa959dfb546568e37419bc85eR261-R262 )
Try Switching between home and settings quickly

home: no null pointer (fixes #803)

---

app/build.gradle
app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/HelpDialog.kt
app/src/main/java/io/treehouses/remote/Fragments/TerminalFragment.java
app/src/main/java/io/treehouses/remote/Views/HelpViewHolder.kt
app/src/main/java/io/treehouses/remote/Views/RecyclerViewClickListener.kt
app/src/main/java/io/treehouses/remote/adapter/HelpAdapter.kt
app/src/main/java/io/treehouses/remote/bases/BaseTerminalFragment.java
app/src/main/java/io/treehouses/remote/pojo/HelpCommand.kt
app/src/main/java/io/treehouses/remote/utils/CommandManager.kt
app/src/main/res/drawable-anydpi/back_button.xml
app/src/main/res/drawable/help.xml
app/src/main/res/layout/activity_terminal_fragment.xml
app/src/main/res/layout/dialog_help.xml
app/src/main/res/layout/row_help.xml
app/src/main/res/values/commands.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

- New Icon in Terminal
- Get JSON String from RPI with `treehouses remote help json`
- Filterable Command Search (Seaches major categories and within the help fields for text)
- RecyclerView
- Description of command
^ Screen needs improvements in next iteration
---
- When an item is long clicked (finger held down on an item for extended period of time), a new view is visible, instead of the full screen description
- Improve design of Description of command
- Highlight Search phrase in description text and/or add search bar there as well
- Bold all commands within the text
- Improve spacing in places
- Try switching between fragments and see if any crashes occur
- Repeatedly click info button
- Anything is welcome!

terminal: add help menu (fixes #745)

---

app/src/main/java/io/treehouses/remote/utils/CommandManager.kt

`open network` not `open wifi network`
https://github.com/treehouses/cli/blob/167109d54ddb6d433b226d4a686b1b0ce05f4e37/modules/wifi.sh#L61

network: new open wifi matcher (#836)

---

app/build.gradle

In accordance with [F-Droid](https://gitlab.com/fdroid/rfp/-/issues/1384)'s update tracker:
> uses variables for versionCode and versionName – our update checker would need literal/static values here

fdroid: literal values of versionCode and versionName

---

app/src/main/java/io/treehouses/remote/adapter/CommandListAdapter.kt

- During kotlinification, convertview was made from a nullable type to a non-nullable type
- convertView can be null, so make it a nullable type

terminal: no crash (fixes #880)

---

app/src/main/res/layout/configure_ssh_key.xml
app/src/main/res/layout/configure_tethering.xml
app/src/main/res/layout/configure_wificountry.xml
app/src/main/res/layout/open_vnc.xml

fixes #911 
Go to **System Fragment** and type in text on all the edit texts and color should be correct in dark mode **ON** as well as **OFF**

system: no white text (fixes #911)

---

app/src/main/res/layout/activity_terminal_fragment.xml

terminal: shrink text (fixes #1008)

---

app/src/main/java/io/treehouses/remote/Fragments/SettingsFragment.kt
app/src/main/res/xml/app_preferences.xml

Instead of having to reinstall every time, a setting to **reactivate tutorials** has been **added** for ease of use
For testing:
Check if tutorials are showing up after reactivated

settings: reactivate tutorials (fixes #977)

---

app/src/main/java/io/treehouses/remote/Fragments/HomeFragment.kt

Fixes #1039 
When the raspberry pi is not connected, click "Get Started" on the home page and it should direct you to the about page instead of saying "Please connect to the raspberry pi"

home: get started (fixes #1039)

---

app/src/main/java/io/treehouses/remote/Fragments/TorTabFragment.kt

Fixes #1024
`readMessage.split(" ".toRegex())` was taking the last space from the output of  `treehouses tor ports`, so breaking at the last loop iteration fixes this.

tunnel: remove empty tor port (fixes #1024)

---

app/src/main/res/layout/activity_services_fragment.xml

services: loading background dark compatible (fixes #1065)

---

app/src/main/java/io/treehouses/remote/Fragments/ServicesFragment.kt

fixes #1076
**Working:**
The first visit to services will take the usual loading time but then the list will be saved in local phone memory to instantly show the next time user comes to services without having to wait for loading but the loading would still be happening in the background and once done it will update the list.
**Testing:**
There should not be any glitches especially memory progress bar not displaying etc

services: cached loading (fixes #1076)

---

app/build.gradle
app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/FeedbackDialogFragment.kt
app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/HelpDialog.kt
app/src/main/java/io/treehouses/remote/Fragments/DialogFragments/SSHDialog.kt
app/src/main/java/io/treehouses/remote/InitialActivity.kt
app/src/main/java/io/treehouses/remote/bases/FullScreenDialogFragment.kt
app/src/main/res/drawable/rectangle_border.xml
app/src/main/res/layout/dialog_ssh.xml
app/src/main/res/values-night/color.xml
app/src/main/res/values/color.xml

- Changed to dialog fragment
- changed to dark mode
To resolve some CodeClimate Issues, a common FullScreenDialogFragment was created. However, it uses `WRAP_CONTENT` instead of `MATCH_PARENT` to let the layout file determine the height of the layout. So please also test:
- HelpDialog in Terminal
- FeedbackDialog

ssh: improved dialog (fixes #1093)

---

app/src/main/res/layout/dialog_help.xml

terminal: selectable command description in help (fixes #1089)

---

app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/RPIDialogFragment.kt

- Always unregister the RPIDialog Receiver

home: always unregister RPIDialog Receiver (fixes #1121)

---

app/src/main/res/layout/dialog_ssh.xml
app/src/main/res/layout/row_ssh.xml
app/src/main/res/values-night/color.xml
app/src/main/res/values/color.xml

- Updated the hint
- Added new colours for dark mode

ssh: dark mode dialog (fixes #1130)

---

app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalView.kt

- When double-tapping, there should be autocompletion, (tab presses) in the ssh terminal

ssh: double tap completion (fixes #1132)

---

app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
app/src/main/res/layout/activity_status_fragment.xml

fixes #1153
fixes #1154 
fixes #1155
1. Added Refresh Button
2. Rounded Corners of Upgrade Button
1. Manage the process of checking everything via refresh function.
2. Refresh Button can call the refresh function to recheck data anytime.
3. After the CLI upgrade refresh is now called instead of recreating fragment.
4. Hostname rename also results in a refresh function call resulting in rename result shown immediately instead of the next visit.
1. Use Refresh Button to Recheck data, maybe change the CLI version on Pi while staying on the status page, and see if refreshing reflects the change.
2. Refresh Button should disappear once used and only come back when the refresh is complete.
3. Rename Hostname and the change should reflect on the status page without having to use the refresh …

status: refresh (fixes #1153) (fixes #1154) (fixes #1155)

---

app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/TerminalBridge.kt

The spacing on ssh terminal is now fixed.

ssh: terminal spacing (fixes #1171)

---

app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/DeleteSSHKey.kt
app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/SSHAllKeys.kt
app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderSSHAllKeyRow.kt
app/src/main/kotlin/io/treehouses/remote/callback/KeyMenuListener.kt
app/src/main/res/color/red_to_grey.xml
app/src/main/res/drawable/ic_baseline_more_vert_24.xml
app/src/main/res/layout/dialog_delete_ssh_key.xml
app/src/main/res/layout/row_key.xml
app/src/main/res/menu/keys_menu.xml
app/src/main/res/values/strings.xml

- Adds functionality to delete SSH Keys
- Does not allow user to delete key without confirmation
- Added context menu (on long click of recyclerview item) and popup menu on the button

ssh: delete ssh key functionality (fixes #1202)

---

app/src/main/kotlin/io/treehouses/remote/bases/BaseBottomSheetDialog.kt
app/src/main/res/drawable/bottomsheet_background.xml
app/src/main/res/layout/dialog_bridge.xml
app/src/main/res/layout/dialog_ethernet.xml
app/src/main/res/layout/dialog_hotspot.xml
app/src/main/res/layout/dialog_wifi.xml
app/src/main/res/values-night/styles.xml
app/src/main/res/values/styles.xml

network: rounded bottomsheet dialogs (fixes #1258)

---

app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt

1. Connect to RPi
2. Press back after connection succeeded
The app should close
There are 2 cases when reopening the app:
- RPi is still connected
- RPi is not connected

home: no back error on dark mode

---

app/build.gradle
app/src/main/kotlin/io/treehouses/remote/Fragments/DialogFragments/EditHostDialog.kt
app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConfig.kt
app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt
app/src/main/res/layout/activity_status_fragment.xml
app/src/main/res/layout/dialog_ssh.xml

Fixes #1248 
Fixes #1302
Fixes #1309 
1. Go to status.
2. Test the pull to refresh feature by pulling down on your screen. Everything should refresh and now it should also be able to display a more user friendly status update to user with "Checking..." instead of being static.
1. Go to SSH.
2. Add a host if you dont have one under "Previously Connected Hosts" with the "Connect" button.
3. Click on a host's pencil icon to edit it.
4. Check to see that
- changing the URI and saving it will instantly update the host list with the new name.
- deleting the host with the trash button will instantly delete it from the host list.

ssh & status: refresh (fixes #1248) (fixes #1302) (fixes #1309)

---

app/src/main/kotlin/io/treehouses/remote/Fragments/SSHConfig.kt
app/src/main/kotlin/io/treehouses/remote/Fragments/StatusFragment.kt

- use view binding for refresh, instead of referencing via ID
- use string command to send network info command on SSH Config

ssh: use string when refresh

---

app/src/main/kotlin/io/treehouses/remote/adapter/ServicesListAdapter.kt

- When "installed" or "available" is typed in, the search will return the all installed or available services respectively
- Used more of a kotlin-ified filter
- Don't show the headers in the search results

services: search update (fixes #1332)

---

app/src/main/kotlin/io/treehouses/remote/Fragments/ServiceCardFragment.kt
app/src/main/kotlin/io/treehouses/remote/Fragments/ServicesDetailsFragment.kt
app/src/main/kotlin/io/treehouses/remote/bases/BaseServicesFragment.kt
app/src/main/kotlin/io/treehouses/remote/callback/ServiceAction.kt
app/src/main/kotlin/io/treehouses/remote/pojo/ServiceInfo.kt
app/src/main/kotlin/io/treehouses/remote/pojo/ServicesData.kt
app/src/main/res/layout/env_var.xml
app/src/main/res/layout/env_var_item.xml
app/src/main/res/layout/service_card.xml

Fixes #1085
1. Run `treehouses upgrade cli` on raspberry pi
2. Checkout `services-env` branch on Android Studio.
3. Run app and go to services.
4. Tap on a service. There should be 4 different cases to look out for.
- A service is not installed. It should not have the "edit env" button.
- A service is installed but not running and does not have environment variables. It should not have the "edit env" button.
- eg. turtleblocksjs, dokuwiki
- A service is installed but not running and does have environment variables. It **should** have the "edit env" button.
- eg. mongodb, librespeed
- A service is running. It should not have the "edit env" button regardless if it uses env variables or not. 
5. For services where environment variables can be changed, click on the "edit env" button and you …

services: add env button (fixes #1085)

---

.gitignore
Vagrantfile

To do: add code climate in a similar way of the [docker compose](https://github.com/treehouses/builder/blob/arm64-bionic/scripts.d/30_docker.sh#L78-L80)

add Vagrantfile for codeclimate (fixes #1271)

---

app/src/main/kotlin/io/treehouses/remote/Network/BluetoothChatService.kt
app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
app/src/main/kotlin/io/treehouses/remote/ui/home/HomeViewModel.kt

- If `treehouses internet` returns false, it shows an AlertDialog with the title "No Internet found"
- **NOTE**: Currently, there are some issues with `treehouses internet` command, so the following command was used instead; `if nc -w 10 -z 8.8.8.5 53; then echo "true"; else echo "false"; fi`
- NOTE: There are also some issues with `treehouses upgrade bluetooth master` as well. If this happens, please try rebooting and try upgrading again.
- Added comments in BaseHomeFragment and HomeViewModel

home: internet check before server sync (fixes #1371)

---

app/src/main/res/layout/activity_ssh_tunnel_fragment.xml
app/src/main/res/layout/activity_tunnel_ssh_fragment.xml

tunnel: background (fixes #1447)

---

app/src/main/kotlin/io/treehouses/remote/Fragments/ServiceCardFragment.kt

fixes #1431 
Makes the links in the Services Info section clickable. 
Before
After

services: links clickable again (fixes #1431)

---

app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
app/src/main/kotlin/io/treehouses/remote/Fragments/TunnelSSHFragment.kt
app/src/main/res/layout/dialog_sshtunnel_hosts.xml
app/src/main/res/layout/dialog_sshtunnel_ports.xml
app/src/main/res/layout/dialog_tor_ports.xml

Fixes #1508 
Fixes #1521
1. Go to Tunnel
2. Add a port or host
3. The dialogs should now have close buttons.

tunnel: dialog close buttons (fixes #1508, #1521)

---

app/src/main/kotlin/io/treehouses/remote/ui/home/BaseHomeFragment.kt
app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
app/src/main/res/values/commands.xml

Please go to settings > Sync Bluetooth File With Local File
The Sync Bluetooth dialog always shows up because we are running `viewModel.sendMessage(getString(R.string.TREEHOUSES_REMOTE_VERSION, BuildConfig.VERSION_CODE))` in onResume. 
Removing this from onResume resolves the bug.

home: no multiple asks for bluetooth sync

---

app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt

fixes #1516 
Fixes the action strings on the Tunnel page so that it matches other message structure. 
Before
After

tunnel: better wording in tor (fixes #1516)

---

app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt

fixes #1507 
The gitter button would become disabled after the first use of it. There was faulty internal communication. Now, the gitter button isn't disabled; after pressed, it sends a toast message that the gitter channel has been notified.

tunnel: tor gitter button improved (fixes #1507)

---

app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesViewModel.kt

- Fixes services SVGs so that none of them breaks anymore

services: no broken svg (fixes #1541)

---

app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt

Make sure device is not null when showing the connecting dialog and the connection failed dialog

home: only show dialog if device is not null (fixes #1553)

---

app/src/main/kotlin/io/treehouses/remote/Fragments/SystemFragment.kt
app/src/main/kotlin/io/treehouses/remote/adapter/ViewHolderTether.kt
app/src/main/kotlin/io/treehouses/remote/utils/DialogUtils.kt

Fixes #1563 
Fixes #1576 
Fixes #1577
1. Go to system.
2. Go to `Share internet with pi (beta)`.
3. Go to `share internet using wifi` and enter a hotspot name and password and then connect. (the connecting toast should now notify the user it will take a couple of minutes)
4. Test out two cases.
- The hotspot password is too short (less than 8 characters). There should now be a toast message saying it is too short.
- The hotspot name name or password is invalid. There should now be a dialog notifying the user of this. Note it may take a couple of minutes to show up.

system: share internet improvements (fixes #1563, #1576, #1577)

---

app/src/main/kotlin/io/treehouses/remote/Fragments/TorTabFragment.kt
app/src/main/kotlin/io/treehouses/remote/adapter/TunnelPortAdapter.kt
app/src/main/kotlin/io/treehouses/remote/utils/DialogUtils.kt
app/src/main/res/drawable/delete_all_icon.xml
app/src/main/res/layout/activity_tor_fragment.xml
app/src/main/res/layout/select_dialog_item_delete_all.xml
app/src/main/res/values-night/strings.xml
app/src/main/res/values/commands.xml
app/src/main/res/values/strings.xml

Fixes #1565 
1. Go to tunnel.
2. Add two ports if you dont have any, as the `delete all ports` functionality only appears when there are at least 2 ports.
3. There should now be `delete all ports` at the bottom of the listview.
4. Test to see if this works and if this button scales with different number of ports in the list.

tunnel: tor delete all ports (fixes #1565)

---

app/src/main/kotlin/io/treehouses/remote/InitialActivity.kt

Fixes #1602 
1. Have data sharing disabled in settings.
2. Go to community.
3. Click enable data sharing in dialog.
4. Community should now automatically open.

options: auto open community (fixes #1602)

---

app/src/main/kotlin/io/treehouses/remote/Fragments/TerminalFragment.kt

Should only send the command/have autocomplete when the autocomplete checkbox in Settings>General is checked

terminal: add autocomplete check (fixes #1619)

---

app/src/main/kotlin/io/treehouses/remote/Fragments/SocksFragment.kt

tunnel: rounding socks profile dialog corners (fixes #1647)

---

app/src/main/kotlin/io/treehouses/remote/SSH/Terminal/BaseTerminalView.kt

Renamed super method parameter to be the same as overridden one.

refactor TerminalView remove warnings

---

app/src/main/res/layout/activity_terminal_fragment.xml

fixes #1573 
Fixes the top-bar layout on a 10inch tablet for terminal view

terminal: redesign top bar (fixes #1573)

---

app/src/main/kotlin/io/treehouses/remote/bases/BaseStatusFragment.kt
app/src/main/kotlin/io/treehouses/remote/fragments/StatusFragment.kt

fixes #1611 
Allow all elements to load before the refresh button is visible.

status: refresh activates when data loaded (fixes #1611)

---

app/src/main/kotlin/io/treehouses/remote/bases/BaseTunnelSSHFragment.kt

fixes #1667 
Error message wasn't clear, and prompted user to try again although that could lead the app to crashing. Now, it says "host not found"

tunnel: clearer ssh error messages (fixes #1667)

---

app/src/main/kotlin/io/treehouses/remote/Tutorials.kt
app/src/main/kotlin/io/treehouses/remote/fragments/TorTabFragment.kt

fixes #1678 
Adds a tutorial in the Tor tunnel tab for first time users

tunnel: tor tutorial added (fixes #1678)

---

app/src/main/kotlin/io/treehouses/remote/bases/BaseTunnelSSHFragment.kt

fixes #1641 
Before, the add port button would not be enabled after failing to delete a port. 
Now, it is enabled after the "incorrect port" toast text is shown.

tunnel: delete false sshport keeps button active (fixes #1641)

---

app/src/main/res/drawable/ic_white.xml
app/src/main/res/layout/activity_terminal_fragment.xml

fixes #1650 
Terminal command list divider color now appears transparent 
Before:
After:

terminal: transparent divider color (fixes #1650)

---

app/src/main/kotlin/io/treehouses/remote/fragments/TunnelSSHFragment.kt
app/src/main/res/values/commands.xml

fixes #1700 
Allow users to delete ssh ports. Before, it would throw an error saying host/port not found. Now, it can delete.

sshtunnel: allow users to delete ports (fixes #1700)

---

app/src/main/res/values/strings.xml

fixes #1730 
update ssh string to remove beta title

ssh: removed beta from title (fixes #1730)

---

app/src/main/kotlin/io/treehouses/remote/sshconsole/SSHConsole.kt

fixes #1708
Description
fixed terminal back button so that it returns to the ssh page, and not the home page.

ssh: back button directs to ssh overview (fixes #1708)

---

app/src/main/kotlin/io/treehouses/remote/Tutorials.kt

fixes #1732 
add skip function to ssh and tor tutorial

ssh and tor: skip button for tutorial (fixes #1732)

---

app/src/main/kotlin/io/treehouses/remote/Tutorials.kt

fixes #1736 
add skip button to the services overview and services details tutorial

services: skip button for tutorials (fixes #1736) 

---

app/src/main/kotlin/io/treehouses/remote/bases/BaseTunnelSSHFragment.kt
app/src/main/kotlin/io/treehouses/remote/fragments/TunnelSSHFragment.kt
app/src/main/res/drawable/gitter_button.xml
app/src/main/res/drawable/gitter_button_disabled.xml
app/src/main/res/drawable/gitter_button_enabled.xml

fixes #1738 
Made it so that the gitter notify button is disabled when there's no host. Once a host gets added, gitter notify gets re-enabled

sshtunnel: host enables gitter notify button (fixes #1738)

---

app/src/main/kotlin/io/treehouses/remote/fragments/TunnelSSHFragment.kt

fixes #1737
Made it so that the page refreshes after successfully adding a host, so that you don't have to go out and come back from a different screen to see the hosts. Also added a small check for adding ports; if the port already exists, gives a toast message indicating so.

sshtunnel: refresh after adding host (fixes #1737)

---

app/src/main/kotlin/io/treehouses/remote/fragments/TunnelSSHFragment.kt
app/src/main/res/drawable/addport_button.xml
app/src/main/res/layout/activity_tunnel_ssh_fragment.xml

fixes #1755 
When there's no host, the add port button is disabled

sshtunnel: defining host enables add port button (fixes #1755)

---

app/src/main/kotlin/io/treehouses/remote/Constants.kt
app/src/main/kotlin/io/treehouses/remote/bases/BaseTunnelSSHFragment.kt
app/src/main/kotlin/io/treehouses/remote/fragments/TunnelSSHFragment.kt
app/src/main/kotlin/io/treehouses/remote/fragments/TunnelSSHFunctions.kt
app/src/main/res/drawable/addhost_button.xml
app/src/main/res/layout/dialog_sshtunnel_hosts.xml
app/src/main/res/values/strings.xml

fixes #1742 
massively update the add host dialog
updates are:
- split host name input into two text inputs, one for the username and another for the domain name. updated info text to reflect this change
- add syntax checks for all inputs, add host button is only enabled if all inputs are filled and don't have errors
- reduced number of code lines in TunnelSSHFragment and BaseTunnelSSHFragment by moving some functions into a new file called TunnelSSHFunctions

sshtunnel: host syntax check added (fixes #1742 )

---

app/src/main/res/layout/navigation_view_header.xml

fixes #1762 
change the height property of the remote TextView box to "wrap content" rather than a fixed size. This causes the symbol, which was a view scroller, to not appear on larger font sizes

main: ready menu for variable font sizes (fixes #1762)

---

app/src/main/kotlin/io/treehouses/remote/bases/BaseSSHConfig.kt

fixes #1771 
Resolve SSH page crashing when switching from light mode to dark mode and vice versa

ssh: avoid crashes (fixes #1771)

---

app/src/main/kotlin/io/treehouses/remote/fragments/TerminalFragment.kt

fixes #1780 
resolve potential crashing with terminal fragment by putitng onDestroy's super function in front

terminal: no crash (fixes #1780)

---

app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt

fixes #1538
added an additional check for ProgressDialog so that it doesn't appear when data is null

home: check for progress dialog (fixes #1538)

---

app/src/main/AndroidManifest.xml
app/src/main/kotlin/io/treehouses/remote/bases/BaseBluetoothChatService.kt
app/src/main/kotlin/io/treehouses/remote/bases/PermissionActivity.kt

fixes #1832
this pr adds 
- `android.permission.BLUETOOTH_CONNECT`- needed to connect with already-paired Bluetooth devices
- `android.permission.BLUETOOTH_SCAN` : needed to scan for bluetooth devices

actions: bluetooth permission newer way (fixes #1832)

---

app/src/main/kotlin/io/treehouses/remote/fragments/TerminalFragment.kt
app/src/main/res/xml/general_preferences.xml

fixes #1834
this pr ensures default autocomplete is set to false

settings: default terminal `autocomplete` to false (fixes #1834)

---

app/src/main/kotlin/io/treehouses/remote/fragments/AboutFragment.kt
app/src/main/res/layout/fragment_about.xml

switched gitter button in about page with discord button

about: introduce discord (fixes #1816)

---

app/src/main/kotlin/io/treehouses/remote/bases/BaseBluetoothChatService.kt
app/src/main/kotlin/io/treehouses/remote/bases/BaseFragment.kt
app/src/main/kotlin/io/treehouses/remote/fragments/dialogfragments/RPIDialogFragment.kt
app/src/main/kotlin/io/treehouses/remote/network/BluetoothChatService.kt

fixes #1860
`'getDefaultAdapter(): BluetoothAdapter!' is deprecated`. so bumping to use the BluetoothManager system service to get a BluetoothAdapter instance to prevent the null exception

actions: use `BluetoothManager` (fixes #1860)

---

.github/workflows/android-release.yml

actions: bump `dogi/sign-android-release` to 5 (fixes #1884)

---

app/src/main/kotlin/io/treehouses/remote/ssh/terminal/TerminalKeyListener.kt
app/src/main/kotlin/io/treehouses/remote/views/terminal/Precomposer.kt
app/src/main/kotlin/io/treehouses/remote/views/terminal/vt320.kt

ssh: modernize code (fixes #1961

---

app/src/main/kotlin/io/treehouses/remote/adapter/ProfilesListAdapter.kt
app/src/main/kotlin/io/treehouses/remote/adapter/ServicesListAdapter.kt
app/src/main/kotlin/io/treehouses/remote/adapter/SystemListAdapter.kt
app/src/main/kotlin/io/treehouses/remote/adapter/TunnelPortAdapter.kt
app/src/main/kotlin/io/treehouses/remote/bases/BaseTerminalBridge.kt
app/src/main/kotlin/io/treehouses/remote/bases/BaseTerminalFragment.kt
app/src/main/kotlin/io/treehouses/remote/bases/FullScreenDialogFragment.kt
app/src/main/kotlin/io/treehouses/remote/fragments/DiscoverFragment.kt
app/src/main/kotlin/io/treehouses/remote/interfaces/FragmentDialogInterface.kt
app/src/main/kotlin/io/treehouses/remote/ssh/SSH.kt
app/src/main/kotlin/io/treehouses/remote/sshconsole/BaseSSHConsole.kt
app/src/main/kotlin/io/treehouses/remote/sshconsole/SSHConsole.kt
app/src/main/kotlin/io/treehouses/remote/ui/home/HomeViewModel.kt
app/src/main/kotlin/io/treehouses/remote/ui/network/NetworkViewModel.kt
app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesDetailsFragment.kt
app/src/main/kotlin/io/treehouses/remote/ui/socks/SocksViewModel.kt
app/src/main/kotlin/io/treehouses/remote/ui/status/StatusViewModel.kt
app/src/main/kotlin/io/treehouses/remote/utils/CommandManager.kt
app/src/main/kotlin/io/treehouses/remote/utils/TunnelSSHCommandManager.kt

fixes #1960
this pr
1. declares unmodified variables using 'val'
2. inlines variable used only in following return
3. Use lowercase() instead of toLowerCase(Locale)
4. resolve deprecated 'getColor(Int): Int'

actions: less warnings is more (fixes #1960)

---

app/src/main/kotlin/io/treehouses/remote/adapter/ServicesListAdapter.kt
app/src/main/kotlin/io/treehouses/remote/fragments/dialogfragments/EditHostDialogFragment.kt
app/src/main/kotlin/io/treehouses/remote/ui/home/HomeFragment.kt
app/src/main/kotlin/io/treehouses/remote/ui/services/ServicesFragment.kt
app/src/main/kotlin/io/treehouses/remote/ui/sshtunnel/BaseSSHTunnelViewModel.kt
app/src/main/kotlin/io/treehouses/remote/ui/sshtunnel/SSHTunnelFragment.kt
app/src/main/kotlin/io/treehouses/remote/ui/sshtunnel/SSHTunnelViewModel.kt
app/src/main/kotlin/io/treehouses/remote/ui/tor/TorFragment.kt

all: no unnecessary non null (fixes #1954)

---

app/src/main/kotlin/io/treehouses/remote/ui/network/NetworkFragment.kt

fixes #1815
This pr ensures that the same fragment manager managing the BottomSheetDialogFragment is used for WifiDialogFragment.

networks: smoother wifi access (fixes #1815)

---

app/build.gradle
app/src/main/kotlin/io/treehouses/remote/MainApplication.kt
app/src/main/kotlin/io/treehouses/remote/bases/BaseBluetoothChatService.kt
app/src/main/kotlin/io/treehouses/remote/network/BluetoothChatService.kt
app/src/main/kotlin/io/treehouses/remote/utils/AppLifeCycleTracker.kt
app/src/main/kotlin/io/treehouses/remote/utils/AppLifecycleObserver.kt

fixes #2059
https://github.com/treehouses/remote/assets/64019708/ff7f85ef-e2de-47d8-be5a-fe91d7d8bd08

all: smoother foreground services (fixes #2059)

---

fastlane/metadata/android/en-US/full_description.txt
fastlane/metadata/android/en-US/short_description.txt

This PR slightly improves formatting of the full description, making it possible to render it as Markdown (supported e.g. at IzzyOnDroid) while keeping it compatible with places not supporting it (e.g. F-Droid.org, PlayStore). It also brings the short description into the limits of Fastlane specs (max 80 chars).

all: smoother fdroid descriptions (fixes #2216)
